[package]
name = "sparq-proved-evaluator-methods"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[build-dependencies]
risc0-build = { version = "=3.0.6", features = ["unstable"] }
risc0-binfmt = "=3.0.5"

[package.metadata.risc0]
methods = ["guest"]
