"""[GPT-6 Astra] Preserve every sample and report the fixed experiment's limits."""
from pathlib import Path
import json
import statistics as st

out=Path(__file__).parent
records=json.loads((out/'measurements.json').read_text())
assert len(records)==168 and all(r['exit_code']==0 for r in records)
points=list(dict.fromkeys((r['case'],r['k']) for r in records))
summary=[]
for case,k in points:
    variants={}
    for variant in ['new','dc','disabled','main']:
        group={r['mode']:r for r in records if (r['case'],r['k'],r['variant'])==(case,k,variant)}
        timing=[r for r in group['timing']['rows'] if r['kind']=='sample']
        count=[r for r in group['count']['rows'] if r['kind']=='sample']
        assert len(timing)==7 and len(count)==3
        assert all(r['oracle']=='pass' for r in timing+count)
        values=[r['whole_query_ns']/1e6 for r in timing]
        metrics=['allocs','reallocs','requested_bytes','peak_live_delta']
        assert len({tuple(r[m] for m in metrics) for r in count})==1
        fixture=next(r for r in group['timing']['rows'] if r['kind']=='fixture')
        verification=next(r for r in group['verify']['rows'] if r['kind']=='verify')
        variants[variant]=dict(whole_query_ms=dict(median=st.median(values),minimum=min(values),maximum=max(values),mean=st.mean(values),sample_stddev=st.stdev(values),all_samples=values),allocations={m:count[0][m] for m in metrics},fixture=fixture,verification=verification,rss_bytes=dict(setup=fixture['setup_max_rss'],after_warmup=timing[0]['pre_query_max_rss'],final_cumulative=timing[-1]['post_query_max_rss'],increase_after_warmup=timing[-1]['post_query_max_rss']-timing[0]['pre_query_max_rss']))
    ratios={f'new_over_{v}':variants['new']['whole_query_ms']['median']/variants[v]['whole_query_ms']['median'] for v in ['dc','disabled','main']}
    ratios['disabled_over_main']=variants['disabled']['whole_query_ms']['median']/variants['main']['whole_query_ms']['median']
    disjoint={v:variants['new']['whole_query_ms']['maximum']<variants[v]['whole_query_ms']['minimum'] or variants['new']['whole_query_ms']['minimum']>variants[v]['whole_query_ms']['maximum'] for v in ['dc','disabled','main']}
    summary.append(dict(case=case,k=k,variants=variants,median_ratios=ratios,new_ranges_disjoint_from=disjoint))
(out/'summary.json').write_text(json.dumps(summary,indent=2)+'\n')

report=dict(
    task='Single authorized option-C lazy per-pattern preparation experiment, PR5983 / issue6465',
    decision='NO_GO: stop top-k admission implementation and measurement; no further iteration without root evaluation',
    decision_basis='Allocation traffic is reduced, but both drained fixtures remain materially slower than disabled fallback with disjoint measured ranges. Base-k512, overlay-k1 and prefix128-overlay also show small slowdowns versus dc with disjoint within-process ranges; intermittent-overlay is slower but ranges overlap. All cases are retained without retiming. This is a local diagnostic engineering result, not a canonical benchmark or an independent review.',
    author='OpenAI GPT-6 Astra, actual xhigh runtime; no additional model sessions or agents',
    head='d08295b6c06ca6f6829de82a210708bab8e44a28',
    parent='dc23141d8c9e640e599085b0ed1616da35d8fc87',
    reviewed_semantic_ancestor='9e8bdfc95c916b62550fb8c3142f804bbbfb2444',
    main_control='cf19a52c6880c496cefaca24046174902bc30958',
    scope=json.loads((out/'composition.json').read_text()),
    implementation='Resolve probe metadata eagerly, retain each scan/vector only at first use in the original pattern order, then reuse it. The original exact scan cardinality and actual-sort checks precede use of that probe. A successful row necessarily visits every probe. The old cap formula, block boundaries/extension, failure counter, shape, budget, view and fanout checks remain. If any probe remains unvisited at an otherwise empty completion, conservatively fall back. Main bind_join is byte-identical. No point scout, storage API or new threshold was introduced.',
    correctness_argument=[
        'Before a row can be emitted, every pattern has been prepared and every original eligibility/probe check has passed. A late selective pattern still forces fallback even if the best candidate would match it.',
        'A failed pattern remains a conjunction rejection in the same pattern order; later work cannot make that candidate match. No output columns or result rows are emitted for partial candidates.',
        'The walk uses exactly the existing logical direction, geometric end/visited_to accounting, full tie extension and failure budget. No scout restarts, skipped block-width accounting or smaller new cutoff.',
        'Unvisited static exclusions cannot authorize a new empty indexed result. Budgeted/unsupported views, repeated variables, unsupported sort/datatype shapes and multi-valued variable probes remain on the existing evaluator.',
    ],
    validation=dict(default='48 integration tests (31 indexed,14 existing topk,3 LIMIT0) +3 test-only preparation tests passed; offline/locked, two build jobs',compact_index='31 indexed integration +3 preparation tests passed; supported constant POS scans are counted before variable PSO absence forces fallback',mutants=json.loads((out/'mutation-results.json').read_text()),mutant_interpretation='Eager preparation fails the actual retained-scan/Id-count assertion; removing late cardinality fails fallback engagement; removing unvisited exclusion fails empty-result fallback engagement. All are real compiled mutations, with restored tests passing. There are no timing assertions.',allocation_controls=json.loads((out/'allocation-control.json').read_text())['checks'],preflight='Known sole failure: Bash3.2 has no mapfile at scripts/check-privacy-claims.sh:92. Not bypassed and not reported green. Explicit-file normal local commit; whitespace check clean.',initial_test_error='New integration fixture initially lacked the SPARQL update separator; corrected before commit. Initial parser-error log retained. This was not a runtime regression or a mutation kill.',limits='No full workspace/clippy/new broad conformance/no-default variant or new Miri/external allocation profiler. Existing unchanged allocator calibration passes in all five newly built counting binaries; its prior negative controls remain preserved.'),
    build=json.loads((out/'build-results.json').read_text()),
    protocol=dict(points=14,variants=['new lazy candidate','dc early-tie candidate','admission-disabled original candidate','exact main cf19'],matrix_processes=168,matrix_query_samples=560,control_processes=12,control_query_samples=18,total_processes=180,total_measured_query_samples=578,timing_samples=392,allocation_samples=186,verify_processes=62,warmup=2,timing_repetitions=7,count_repetitions=3,n=50000,k='1 plus favorable base/overlay512',threads=1,build_jobs=2,build_deadline_seconds=900,fixture_details='Original eight points unchanged. New prefix128/prefix800 counts live rows after every-fifth overlay deletions; intermittent misses every eighth live descending rank starting with the best row. Six probe predicates, seven triples/entity. Overlay retains base snapshot and70,000 tombstones with40,000 live seed rows.',harness='Exact same extended harness/lock/features built against every comparison source under each owned target/bench-wrapper. Original binaries were not reused for changed fixtures and were not overwritten. Target cache reuse is separate from immutable stored binaries.',query_window='Whole query call including parsing, evaluation and result construction; independent total-order checking/formatting/destruction outside the window. Timing/counting binaries separate. Separate verify runs infer path via existing BGP trace.',ordering='One round-robin source ordering by fixture, sequential execution, no concurrent build. No outlier removal, retiming, adaptive threshold or noisy-run hunting. Per-process load averages stored; no affinity/frequency/thermal/host-wide quietness guarantee.'),
    results=summary,
    other_observations='Versus dc: base-k512 median+1.7%, overlay-k1+5.0%, prefix128-overlay+2.3%, all with disjoint repetition ranges; intermittent-overlay+5.3% has overlapping ranges. Tie base/overlay remain1.14x/1.16x disabled medians, with base ranges overlapping and overlay disjoint. First base-k1 disabled/main timing ratio is1.82 despite identical allocation metrics: process/host variability prevents precise causal attribution or universal speedup claims.',
    allocation_interpretation='Against the real eager-placement control, drained base avoids800,000 requested bytes/4 allocations; overlay avoids3,040,000 bytes/8 allocations. Peaks are unchanged because the unused preparation was already freed before fallback peak. Favorable new/eager allocation metrics are equal. Against dc, admitted fixtures retain a144-byte increase from larger probe metadata; no claim of globally identical allocation totals.',
    memory_limits='Requested bytes are allocation traffic (including full new realloc sizes), not simultaneous live memory. peak_live_delta is requested live heap above query baseline, excluding allocator metadata, stack, mappings and allocator-internal transient realloc peaks. macOS getrusage RSS is cumulative process high-water, recorded after setup/warmup/query; cannot isolate a resettable query-only RSS peak. Flat cumulative RSS does not imply zero query memory.',
    timing_limits='All repetition values, ranges and sample standard deviations are included. Even identical-allocation main/disabled sources can drift due to code layout and host noise; ratios are diagnostic observations. No precise canonical speedup, production throughput or generalized scaling claim.',
    next_lane='Stop top-k admission work at this frozen candidate. Root may select a separate ordinary SPARQL scan/bind-join overlay-cost lane: count_correction scans every tombstone for each range lookup. Dedupe existing work before any new implementation; do not extend this experiment into an overlay rewrite.',
    unresolved=['Drained prefix probing still precedes fallback','F3 public exact-tie ordering documentation','F4 explicit indexed-path trace','F5 remaining path-pinned semantic/source-context work','Any future independent Opus review/admission; no model review in this experiment'],
    provenance_files=['provenance.json','source-hashes.json','harness-hashes.json','build-results.json','host.json','preserved-evidence.json'],
)
(out/'report.json').write_text(json.dumps(report,indent=2)+'\n')
lines=['# Option C experiment: NO-GO for top-k admission','',f"Frozen local HEAD `{report['head']}`, parent `{report['parent']}`. Actual GPT-6 Astra xhigh. This is the single authorized lazy-preparation experiment; no new model review or remote mutation. Stop implementation/measurement after this report.",'','The patch delays each prepared scan/vector until a candidate reaches its pattern. Pattern order and all existing block/tie/failure/shape/budget/view/fanout rules remain; per-probe sort/cardinality guards run before use. A successful row must visit every probe. Unvisited exclusions conservatively fall back. No new storage API, point scout or threshold. Main bind_join is byte-identical.','', 'Default focused validation:48 integration +3 preparation tests. Compact-index:31 integration +3 preparation tests. Three actual mutants were killed: eager initialization, omitted late cardinality, and omitted unvisited exclusion. Restored controls pass. The initial fixture update separator error was corrected before commit and preserved in its log. Author preflight has only the known Bash3 mapfile limitation and is not presented as green.','', 'Eager control restores800,000 requested bytes/4 allocations in drained base and3,040,000 bytes/8 allocations in drained overlay. Favorable new/eager metrics are equal. Against dc, larger metadata adds144 bytes on admitted fixtures. Query heap peaks in the drained fallback cases do not improve; the removed preparation had already been freed before fallback peak.','', 'All180 processes /578 measured query samples passed their result/path checks (168 matrix processes/560 samples plus12 allocation-control processes/18 samples). Identical extended harness compiled against all four sources; nine optimized binaries fit under the15-minute total cap. One sequential lane, two build jobs, Rayon1, warmup2, timing7/count3 repetitions. All samples retained.','', '| Fixture | New ms | dc ms | Disabled ms | Main ms | New/dc | New/disabled |','|---|---:|---:|---:|---:|---:|---:|']
for r in summary:
    values=[r['variants'][v]['whole_query_ms']['median'] for v in ['new','dc','disabled','main']]
    lines.append(f"| {r['case']} k{r['k']} | "+' | '.join(f'{x:.3f}' for x in values)+f" | {r['median_ratios']['new_over_dc']:.3f} | {r['median_ratios']['new_over_disabled']:.3f} |")
lines += ['', 'The material drained penalty remains (~1.23× base and1.30× overlay versus disabled, disjoint ranges). Versus dc, base-k512(+1.7%), overlay-k1(+5.0%) and prefix128-overlay(+2.3%) also have slower, disjoint within-process ranges; intermittent-overlay(+5.3%) overlaps. Tie medians remain1.14×/1.16× disabled. First base-k1 disabled/main timing differs1.82× despite identical allocation metrics, so causal precision is limited. These observations reinforce the stop; benefits elsewhere do not authorize admission. Timing ratios are local diagnostic observations; full ranges/standard deviations and baseline drift are in summary.json. No noisy-run confirmation or broader sweep was performed.','', 'Whole-query timing excludes result checking/drop. Allocation counting uses a separate binary and measures requested traffic/live heap, not allocator overhead. RSS is cumulative process high-water after setup/warmup/query, not an isolated query-only peak. Source/harness/binary hashes, raw outputs and exact build commands accompany this packet. The old semantic, diagnostic, early-tie and design artifacts remain immutable.','', 'Next lane recommendation: after root dedupe, investigate ordinary SPARQL scan/bind-join tombstone range-counting cost separately. No further top-k design/implementation iteration is authorized here. F3–F5 remain unresolved.','', '## Combined runtime delta from the independently reviewed semantic ancestor','', '```diff',(out/'combined-runtime.diff').read_text(),'```','', '## Exact harness extension from the prior diagnostic harness','', '```diff',(out/'harness-extension.diff').read_text(),'```','', '## Complete affected functions, tests and extended measurement harness','',(out/'source-context.md').read_text()]
(out/'review-packet.md').write_text('\n'.join(lines)+'\n')
print(json.dumps({'head':report['head'],'points':len(summary),'packet_bytes':(out/'review-packet.md').stat().st_size},indent=2))
