// [OPUS-4.8] written while Fable 5 unavailable — re-review when Fable returns.
//! sq-ot3x: per-config bb-gates MATRIX ↔ snapshot ↔ dispatch consistency gate.
//!
//! `bench/zk-compose/bb_gates_matrix.json` is the maintainer-requested (#769)
//! comparison surface: for every `(commitment-method, circuit)` CONFIGURATION,
//! whether the pair is LEGAL (dispatch-compatible under the fail-closed resolver
//! rule — NOT a claim the config is wired end-to-end and provable today; see the
//! README honesty note) and — per circuit — its ultra_honk
//! `bb-gates` `circuit_size`. It is GENERATED by
//! `bench/zk-compose/scripts/bb_gates_matrix.py`, which joins each circuit's
//! `circuit_size` from the regression-gated snapshot
//! (`tests/gate_count_snapshot.json`) and mirrors the fail-closed dispatch rule
//! (`src/dispatch.rs`, `resolve_circuit`, sq-cfmv).
//!
//! This test re-checks the COMMITTED matrix against the COMMITTED snapshot
//! WITHOUT the nargo/bb toolchain (it only parses two checked-in JSONs), so it
//! runs in the normal suite and is deterministic / non-flaky. It enforces the
//! anti-drift + honesty contract:
//!
//!   * every matrix circuit EXISTS in the snapshot and every `circuit_size`
//!     EQUALS the snapshot value (no hand-typed number that could disagree);
//!   * every snapshot member is COVERED by the matrix (a new circuit cannot be
//!     silently omitted — the value of the matrix is its completeness, cf. G5);
//!   * the LEGALITY cells obey the design §3.1 rule (value-lane members legal
//!     only for value-handle methods; string-lane members illegal for
//!     `value-only`) — the SAME rule `dispatch::resolve_circuit` enforces;
//!   * an ILLEGAL cell carries a fail-closed `reason` and NO per-cell gate
//!     number; a LEGAL cell carries none;
//!   * the `summary` counts and the `comparison` numbers match the rows (a stale
//!     summary or a fabricated comparison number is caught).
//!
//! Under the `dual-leaf` feature it ADDITIONALLY cross-checks every constructible
//! `(method, circuit)` cell against the REAL `dispatch::resolve_circuit`
//! resolver — tying the committed legality to the single source of truth, not a
//! transcribed rule.
//!
//! If this fails after an INTENTIONAL circuit change, re-run
//! `bench/zk-compose/scripts/gate_counts.sh` (re-baseline the snapshot + bench
//! JSON) and then `bench/zk-compose/scripts/bb_gates_matrix.py >
//! bench/zk-compose/bb_gates_matrix.json` to re-join the new numbers.
//!
//! HONESTY: the numbers are NON-CANONICAL work-box bb-gates; the ZK estate is NOT
//! externally audited (sq-qhy4); `dual-leaf`/`value-only` carry the INV-VL
//! downgrade (CR-G8). This gate asserts consistency + honesty, NOT any soundness
//! or privacy property.

use serde::Deserialize;
use std::collections::BTreeMap;

/// The regression-gate snapshot (the source of truth for `circuit_size`).
const SNAPSHOT_JSON: &str = include_str!("gate_count_snapshot.json");
/// The generated per-config gate matrix under test.
const MATRIX_JSON: &str = include_str!("../../../bench/zk-compose/bb_gates_matrix.json");

/// Kept in lockstep with `VALUE_LANE_PREFIX` in `bb_gates_matrix.py` and
/// `dispatch::is_value_lane_member` (the value-lane members are the
/// `filter_value_dl_*` family).
const VALUE_LANE_PREFIX: &str = "filter_value_dl_";

#[derive(Deserialize)]
struct Snapshot {
    members: BTreeMap<String, u64>,
}

#[derive(Deserialize)]
struct Matrix {
    methods: Vec<Method>,
    matrix: BTreeMap<String, Circuit>,
    comparison: BTreeMap<String, Comparison>,
    summary: Summary,
}

#[derive(Deserialize)]
struct Method {
    key: String,
    iri: String,
    #[allow(dead_code)]
    production_selectable: bool,
    #[allow(dead_code)]
    removes_inv_vl: bool,
}

#[derive(Deserialize)]
struct Circuit {
    circuit_size: u64,
    lane: String,
    configs: BTreeMap<String, Cell>,
}

/// `deny_unknown_fields` is load-bearing: it is what makes
/// `illegal_cells_carry_a_reason_not_a_cost` NON-vacuous. The only accepted cell
/// fields are `legal` and an optional `reason`; a cell carrying a fabricated
/// per-cell cost (`circuit_size`, `gate_count`, …) FAILS to parse instead of
/// being silently dropped by serde (see `cell_rejects_a_fabricated_per_cell_cost`).
#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct Cell {
    legal: bool,
    #[serde(default)]
    reason: Option<String>,
}

#[derive(Deserialize)]
struct Comparison {
    value_lane_member: String,
    value_lane_circuit_size: u64,
    #[serde(default)]
    string_lane_member: Option<String>,
    #[serde(default)]
    string_lane_circuit_size: Option<u64>,
    #[serde(default)]
    gate_reduction_x: Option<f64>,
}

#[derive(Deserialize)]
struct Summary {
    circuits: usize,
    methods: usize,
    configs: usize,
    legal_configs: usize,
    illegal_configs: usize,
}

fn load() -> (Snapshot, Matrix) {
    let snapshot: Snapshot =
        serde_json::from_str(SNAPSHOT_JSON).expect("gate_count_snapshot.json parses");
    let matrix: Matrix =
        serde_json::from_str(MATRIX_JSON).expect("bb_gates_matrix.json parses");
    (snapshot, matrix)
}

fn is_value_lane(member: &str) -> bool {
    member.starts_with(VALUE_LANE_PREFIX)
}

/// The design §3.1 legality rule (mirrors `dispatch::resolve_circuit`): value-lane
/// members are legal only for value-handle methods; string-lane members are
/// illegal for `value-only`.
fn expect_legal(method_key: &str, member: &str) -> bool {
    if member.starts_with("result_v1_") {
        // [GPT-6] The additive result relation authenticates whole string-canonical
        // graphs; it cannot reuse a dual-leaf graph's lexical handle as its root.
        method_key == "string-canonical"
    } else if is_value_lane(member) {
        matches!(method_key, "dual-leaf" | "value-only")
    } else {
        matches!(method_key, "string-canonical" | "dual-leaf")
    }
}

/// Every matrix circuit MUST exist in the snapshot with the SAME `circuit_size`
/// (the join is faithful — no hand-typed number), AND its `lane` label must match
/// the `filter_value_dl_*` classification.
#[test]
fn matrix_circuit_sizes_match_snapshot() {
    let (snapshot, matrix) = load();
    let mut errors = Vec::new();
    for (member, c) in &matrix.matrix {
        match snapshot.members.get(member) {
            Some(&snap) if snap == c.circuit_size => {}
            Some(&snap) => errors.push(format!(
                "{member}: matrix circuit_size={} != snapshot={snap}",
                c.circuit_size
            )),
            None => errors.push(format!(
                "{member}: present in the matrix but ABSENT from gate_count_snapshot.json"
            )),
        }
        let want_lane = if is_value_lane(member) { "value" } else { "string" };
        if c.lane != want_lane {
            errors.push(format!(
                "{member}: lane={:?} but the {VALUE_LANE_PREFIX} classification wants {want_lane:?}",
                c.lane
            ));
        }
    }
    assert!(
        errors.is_empty(),
        "matrix ↔ snapshot mismatch (re-run bench/zk-compose/scripts/bb_gates_matrix.py):\n{}",
        errors.join("\n")
    );
}

/// COMPLETENESS (the value of the matrix): every snapshot member is a matrix row,
/// so a newly-added circuit cannot silently escape the per-config matrix — the
/// same coverage guarantee `snapshot_covers_every_member` gives the gate-count
/// snapshot (sq-ncvq.8 / G5).
#[test]
fn matrix_covers_every_snapshot_member() {
    let (snapshot, matrix) = load();
    let missing: Vec<&String> = snapshot
        .members
        .keys()
        .filter(|m| !matrix.matrix.contains_key(*m))
        .collect();
    assert!(
        missing.is_empty(),
        "snapshot members absent from the matrix (re-run bench/zk-compose/scripts/bb_gates_matrix.py \
         so every circuit gets a per-config row): {missing:?}"
    );
}

/// The LEGALITY cells obey the design §3.1 / `dispatch::resolve_circuit` rule, and
/// every method column named in `methods` is present on every circuit row (a
/// total matrix). This is the transcribed-rule check; the `dual-leaf`-gated test
/// below ties it to the real resolver.
#[test]
fn legality_cells_follow_the_dispatch_rule() {
    let (_snapshot, matrix) = load();
    let method_keys: Vec<&str> = matrix.methods.iter().map(|m| m.key.as_str()).collect();
    let mut errors = Vec::new();
    for (member, c) in &matrix.matrix {
        for key in &method_keys {
            match c.configs.get(*key) {
                None => errors.push(format!("{member}: missing config cell for method {key}")),
                Some(cell) => {
                    let want = expect_legal(key, member);
                    if cell.legal != want {
                        errors.push(format!(
                            "{member} × {key}: legal={} but the dispatch rule wants {want}",
                            cell.legal
                        ));
                    }
                }
            }
        }
        // No stray method key outside the declared set.
        for key in c.configs.keys() {
            if !method_keys.contains(&key.as_str()) {
                errors.push(format!("{member}: config cell for unknown method {key:?}"));
            }
        }
    }
    assert!(
        errors.is_empty(),
        "legality cell disagrees with the fail-closed dispatch rule:\n{}",
        errors.join("\n")
    );
}

/// Honesty gate (load-bearing): an ILLEGAL cell carries a fail-closed `reason` and
/// NO gate number (the config does not exist, so it has no cost); a LEGAL cell
/// carries no `reason`. The circuit's intrinsic cost lives ONCE on the row's
/// `circuit_size`, never fabricated per illegal cell.
#[test]
fn illegal_cells_carry_a_reason_not_a_cost() {
    let (_snapshot, matrix) = load();
    let mut errors = Vec::new();
    for (member, c) in &matrix.matrix {
        for (key, cell) in &c.configs {
            if cell.legal {
                if cell.reason.is_some() {
                    errors.push(format!(
                        "{member} × {key}: LEGAL cell must not carry a reason ({:?})",
                        cell.reason
                    ));
                }
            } else {
                match cell.reason.as_deref() {
                    Some("IllegalPair") | Some("IdentityOpAtValueLane") | Some("UnknownMethod") => {}
                    other => errors.push(format!(
                        "{member} × {key}: ILLEGAL cell must carry a fail-closed reason \
                         (a DispatchError variant), found {other:?}"
                    )),
                }
            }
        }
    }
    assert!(
        errors.is_empty(),
        "illegal/legal cell shape violates the honesty contract:\n{}",
        errors.join("\n")
    );
}

/// Mutation guard: the illegal-cell cost check above is only non-vacuous because
/// `Cell` is `#[serde(deny_unknown_fields)]`. Without it, serde silently drops an
/// unknown field, so an illegal cell smuggling a fabricated per-cell cost would
/// still pass `illegal_cells_carry_a_reason_not_a_cost`. This test pins that the
/// only accepted cell fields are `legal` + optional `reason`: any `circuit_size`
/// / `gate_count` on a cell is a HARD parse failure.
#[test]
fn cell_rejects_a_fabricated_per_cell_cost() {
    // A cell carrying a fabricated cost must be REJECTED, not silently ignored.
    assert!(
        serde_json::from_str::<Cell>(r#"{"legal": true, "circuit_size": 999}"#).is_err(),
        "a cell carrying a fabricated circuit_size must fail to parse (deny_unknown_fields)"
    );
    assert!(
        serde_json::from_str::<Cell>(r#"{"legal": false, "reason": "IllegalPair", "gate_count": 42}"#)
            .is_err(),
        "an illegal cell carrying a fabricated gate_count must fail to parse"
    );
    // The two honest cell shapes still parse.
    assert!(
        serde_json::from_str::<Cell>(r#"{"legal": true}"#).is_ok(),
        "a legal cell is just {{legal: true}}"
    );
    assert!(
        serde_json::from_str::<Cell>(r#"{"legal": false, "reason": "IllegalPair"}"#).is_ok(),
        "an illegal cell is {{legal: false, reason}} with no cost"
    );
}

/// The `summary` counts match the actual rows/cells, so a stale hand-edited
/// summary is caught.
#[test]
fn summary_matches_rows() {
    let (_snapshot, matrix) = load();
    let circuits = matrix.matrix.len();
    let methods = matrix.methods.len();
    let mut legal = 0usize;
    let mut illegal = 0usize;
    for c in matrix.matrix.values() {
        for cell in c.configs.values() {
            if cell.legal {
                legal += 1;
            } else {
                illegal += 1;
            }
        }
    }
    assert_eq!(matrix.summary.circuits, circuits, "summary.circuits mismatch");
    assert_eq!(matrix.summary.methods, methods, "summary.methods mismatch");
    assert_eq!(
        matrix.summary.configs,
        circuits * methods,
        "summary.configs mismatch"
    );
    assert_eq!(matrix.summary.legal_configs, legal, "summary.legal_configs mismatch");
    assert_eq!(
        matrix.summary.illegal_configs, illegal,
        "summary.illegal_configs mismatch"
    );
}

/// The `comparison` block's numbers are JOINED from the snapshot (never
/// hand-typed): each member exists in the snapshot with the recorded size, and
/// the `gate_reduction_x` equals string/value rounded to 2 dp. A comparison whose
/// members don't exist, or whose ratio is fabricated, is a hard failure.
#[test]
fn comparison_numbers_are_joined_from_snapshot() {
    let (snapshot, matrix) = load();
    let mut errors = Vec::new();
    for (dt, cmp) in &matrix.comparison {
        match snapshot.members.get(&cmp.value_lane_member) {
            Some(&snap) if snap == cmp.value_lane_circuit_size => {}
            Some(&snap) => errors.push(format!(
                "{dt}: value_lane_circuit_size={} != snapshot={snap}",
                cmp.value_lane_circuit_size
            )),
            None => errors.push(format!(
                "{dt}: value_lane_member {} absent from snapshot",
                cmp.value_lane_member
            )),
        }
        // The value-lane member must actually BE a value-lane member.
        if !is_value_lane(&cmp.value_lane_member) {
            errors.push(format!(
                "{dt}: value_lane_member {} is not a {VALUE_LANE_PREFIX} member",
                cmp.value_lane_member
            ));
        }
        if let (Some(sm), Some(ss)) = (&cmp.string_lane_member, cmp.string_lane_circuit_size) {
            match snapshot.members.get(sm) {
                Some(&snap) if snap == ss => {}
                Some(&snap) => {
                    errors.push(format!("{dt}: string_lane_circuit_size={ss} != snapshot={snap}"))
                }
                None => errors.push(format!("{dt}: string_lane_member {sm} absent from snapshot")),
            }
            if let Some(rx) = cmp.gate_reduction_x {
                let want = (ss as f64 / cmp.value_lane_circuit_size as f64 * 100.0).round() / 100.0;
                if (rx - want).abs() > 1e-9 {
                    errors.push(format!(
                        "{dt}: gate_reduction_x={rx} != string/value rounded ({want})"
                    ));
                }
            }
        }
    }
    assert!(
        errors.is_empty(),
        "comparison block disagrees with the regression-gated snapshot:\n{}",
        errors.join("\n")
    );
}

/// Sanity: the matrix names exactly the three commitment methods with their
/// registry `zk:scheme` IRIs, and the #769 headline value-lane reduction is
/// present. Guards against a future edit silently dropping the comparison the
/// bead exists to produce.
#[test]
fn matrix_spans_the_three_methods_and_the_headline_comparison() {
    let (_snapshot, matrix) = load();
    let by_key: BTreeMap<&str, &str> = matrix
        .methods
        .iter()
        .map(|m| (m.key.as_str(), m.iri.as_str()))
        .collect();
    assert_eq!(
        by_key.get("string-canonical").copied(),
        Some("https://sparq.dev/ns/zk#poseidon2-rdfc10-v1"),
        "string-canonical method/IRI must be present"
    );
    assert_eq!(
        by_key.get("dual-leaf").copied(),
        Some("https://sparq.dev/ns/zk#poseidon2-dualleaf-v1"),
        "dual-leaf method/IRI must be present"
    );
    assert_eq!(
        by_key.get("value-only").copied(),
        Some("https://sparq.dev/ns/zk#poseidon2-valuehook-v1"),
        "value-only research-dial method/IRI must be present"
    );
    // The integer datatype's value-lane reduction is the #769 headline.
    let int = matrix
        .comparison
        .get("integer")
        .expect("integer comparison row must be present");
    assert_eq!(int.value_lane_member, "filter_value_dl_int");
    assert!(
        int.gate_reduction_x.unwrap_or(0.0) > 1.0,
        "the dual-leaf value lane must be cheaper than the string-canonical blake3 lane"
    );
}

// --- resolver cross-check (ties the committed legality to the real source of
//     truth; runs where the `dual-leaf` feature is enabled) -------------------

/// Under `dual-leaf`, cross-check every committed legality cell we can construct a
/// `(CommitmentMethod, CircuitId)` for against the REAL
/// `dispatch::resolve_circuit` — so the transcribed rule above can never diverge
/// from the resolver it mirrors. Members/methods not constructible under the
/// enabled features (path-reach needs `extended-fragment`; `value-only` needs
/// `commitment-value-only`) are skipped, not fabricated.
#[cfg(feature = "dual-leaf")]
#[test]
fn committed_legality_matches_resolve_circuit() {
    use sparq_zk::commit::CommitmentMethod;
    use sparq_zk_compose::dispatch::{resolve_circuit, DispatchError};
    use sparq_zk_compose::manifest::CircuitId;

    let (_snapshot, matrix) = load();

    // The methods constructible in THIS build, keyed by their matrix key.
    #[allow(unused_mut)]
    let mut methods: Vec<(&str, CommitmentMethod)> = vec![
        ("string-canonical", CommitmentMethod::StringCanonicalV1),
        ("dual-leaf", CommitmentMethod::DualLeafV1),
    ];
    #[cfg(feature = "commitment-value-only")]
    methods.push(("value-only", CommitmentMethod::ValueOnlyV1));

    // Map the matrix member names we can build a CircuitId for. Parameterized
    // families use one representative per family (legality is family-uniform — it
    // depends only on the lane, not on k/n/r/d).
    let circuit_for = |member: &str| -> Option<CircuitId> {
        match member {
            "filter_value_dl_int" => Some(CircuitId::FilterValueDl),
            "filter_value_dl_f64" => Some(CircuitId::FilterValueDlF64),
            "filter_value_dl_decimal" => Some(CircuitId::FilterValueDlDecimal),
            "filter_int_d2" => Some(CircuitId::FilterInt { d: 2 }),
            "filter_f64_d2" => Some(CircuitId::FilterF64 { d: 2 }),
            "scan_k1_n16_r4" => Some(CircuitId::Scan { k: 1, n: 16, r: 4 }),
            "join_eq_na16_nb16" => Some(CircuitId::JoinEq { n_a: 16, n_b: 16 }),
            "holder_pok" => Some(CircuitId::HolderPok),
            _ => None,
        }
    };

    let mut checked = 0usize;
    let mut errors = Vec::new();
    for (member, c) in &matrix.matrix {
        let Some(id) = circuit_for(member) else { continue };
        for (key, method) in &methods {
            let Some(cell) = c.configs.get(*key) else { continue };
            let resolved_legal = match resolve_circuit(*method, &id) {
                Ok(_) => true,
                Err(DispatchError::IllegalPair { .. })
                | Err(DispatchError::IdentityOpAtValueLane { .. })
                | Err(DispatchError::UnknownMethod { .. }) => false,
            };
            if resolved_legal != cell.legal {
                errors.push(format!(
                    "{member} × {key}: committed legal={} but resolve_circuit says {resolved_legal}",
                    cell.legal
                ));
            }
            checked += 1;
        }
    }
    assert!(
        checked > 0,
        "the resolver cross-check constructed no cells — the member→CircuitId map is stale"
    );
    assert!(
        errors.is_empty(),
        "committed matrix legality diverges from dispatch::resolve_circuit \
         (re-run bench/zk-compose/scripts/bb_gates_matrix.py):\n{}",
        errors.join("\n")
    );
}

// [GPT-6] Keep all measured result buckets in the comparison without inventing
// compatibility with the legacy dual-leaf dispatch surface.
#[test]
fn successful_result_members_only_admit_string_canonical_commitments() {
    let (_, matrix) = load();
    let members: Vec<_> = matrix
        .matrix
        .iter()
        .filter(|(member, _)| member.starts_with("result_v1_"))
        .collect();
    assert_eq!(members.len(), 4);
    for (_, row) in members {
        assert!(row.configs["string-canonical"].legal);
        assert!(!row.configs["dual-leaf"].legal);
        assert!(!row.configs["value-only"].legal);
    }
}
