//! [OPUS-4.8] sq-d3d8 (epic sq-3183): OPT-IN federation discovery descriptors.
//!
//! Two read-only RDF documents that make a `sparq-server` instance a *discoverable*
//! federation node:
//!
//!   * **VoID** (`GET /.well-known/void`) — a [W3C VoID](https://www.w3.org/TR/void/)
//!     description of the served dataset (triple/entity/class/property counts +
//!     class/property partitions), generated by [`sparq_introspect::Introspection::to_void`].
//!   * **SPARQL Service Description** (a `GET` on the SPARQL endpoint with **no `query`
//!     parameter**, per [SPARQL 1.1 Protocol §2.1.2 / Service Description
//!     §2](https://www.w3.org/TR/sparql11-service-description/)) — an `sd:Service`
//!     advertising the endpoint URL, the supported SPARQL query languages, the supported
//!     result formats, and the default dataset (linked to the VoID document).
//!
//! ## OPT-IN — feature `federation-descriptors` AND a config flag, both OFF by default
//!
//! This whole module is compiled only behind the `federation-descriptors` cargo feature.
//! Even with the feature on, the endpoints are served only when
//! [`ServerConfig::federation_descriptors`](crate::ServerConfig::federation_descriptors) is
//! `true` (CLI `--federation-descriptors` / env `SPARQ_FEDERATION_DESCRIPTORS=1`). With the
//! feature ON but the flag OFF (the default even when compiled in):
//!
//!   * `GET /.well-known/void` returns `404` (the route is mounted but the handler refuses);
//!   * a `GET /sparql` with no `query` returns the historical `400 missing 'query'`.
//!
//! So discovery is never exposed unless an operator deliberately turns it on, and a build
//! without the feature pays *zero* cost — no `sparq-introspect` dependency, no new routes,
//! byte-identical to before. `sparq-core` / `sparq-engine` are untouched: the descriptor
//! generation reads a pinned snapshot `&Graph` through the existing public introspection API.
//!
//! ## Cost
//!
//! Generating the VoID/SD scans the snapshot (the same cost as a `?s ?p ?o` dump plus the
//! per-class/predicate aggregation `Introspection::build` already does). It is therefore a
//! request-time scan, not amortised — appropriate for an occasionally-polled discovery
//! endpoint, and another reason it is opt-in rather than always-on.

use oxrdf::{Term, Triple};

use sparq_core::Graph;
use sparq_introspect::Introspection;

use crate::negotiate::{negotiate_graph, GraphFormat};

/// `sd:` — the SPARQL 1.1 Service Description vocabulary namespace.
const SD_NS: &str = "http://www.w3.org/ns/sparql-service-description#";
/// `void:` — the VoID vocabulary namespace (the dataset the SD links to).
const VOID_NS: &str = "http://rdfs.org/ns/void#";
/// `dcterms:` — used for the `dcterms:source` link from the SD to the VoID document.
const DCTERMS_NS: &str = "http://purl.org/dc/terms/";
const RDF_TYPE: &str = "http://www.w3.org/1999/02/22-rdf-syntax-ns#type";

/// `sd:SPARQL11Query` — the SPARQL 1.1 Query language the engine evaluates.
const SD_SPARQL11_QUERY: &str = "http://www.w3.org/ns/sparql-service-description#SPARQL11Query";
/// `sd:SPARQL11Update` — the SPARQL 1.1 Update language the protocol's write path executes.
const SD_SPARQL11_UPDATE: &str = "http://www.w3.org/ns/sparql-service-description#SPARQL11Update";

/// [OPUS-4.8] sq-2msb (gh-917): the SPARQL 1.2 Service Description (ED) version-agnostic
/// language terms. SPARQL 1.2 SD splits the old "language AND version" `sd:Language`
/// individuals (`sd:SPARQL11Query`/`sd:SPARQL11Update`) so that `sd:Language` now names only
/// the LANGUAGE (`sd:SPARQLQuery`/`sd:SPARQLUpdate`) and the VERSION moves to a separate
/// `sd:supportedVersion`. We advertise BOTH the version-agnostic 1.2 terms and the legacy 1.1
/// terms via `sd:supportedLanguage`, so a 1.1-only client still recognises the endpoint and a
/// 1.2-aware client also reads the version posture. See
/// <https://w3c.github.io/sparql-service-description/spec/> §Versioning.
const SD_SPARQL_QUERY: &str = "http://www.w3.org/ns/sparql-service-description#SPARQLQuery";
/// [OPUS-4.8] sq-2msb: the SPARQL 1.2 SD version-agnostic Update language term.
const SD_SPARQL_UPDATE: &str = "http://www.w3.org/ns/sparql-service-description#SPARQLUpdate";

/// [OPUS-4.8] sq-2msb (gh-917): the SPARQL language-version individuals in the `sparql:`
/// namespace (`http://www.w3.org/ns/sparql#`), advertised via `sd:supportedVersion`. These are
/// the version IRIs the SPARQL 1.2 SD (ED) defines: `version-1.0`, `version-1.1`,
/// `version-1.2-basic` (SPARQL 1.2 Query with RDF 1.2 BASIC conformance) and `version-1.2` (full
/// RDF 1.2 conformance). See [`Capabilities::sparql_versions`] for the emitted labels.
const SPARQL_VERSION_1_0: &str = "http://www.w3.org/ns/sparql#version-1.0";
/// [OPUS-4.8] sq-2msb: `sparql:version-1.1`.
const SPARQL_VERSION_1_1: &str = "http://www.w3.org/ns/sparql#version-1.1";
/// [GPT-6] Existing `sparql:version-1.2` service label; see the scoped contract below.
const SPARQL_VERSION_1_2: &str = "http://www.w3.org/ns/sparql#version-1.2";

/// Existing service-description version labels, in ascending order.
///
/// [GPT-6] The legacy public constant name and emitted IRIs are retained for
/// compatibility, not a claim of complete SPARQL 1.2 conformance. Unannounced
/// queries retain REC 2013 expression semantics; `VERSION "1.2"` selects only
/// the implemented, pinned 2026-09-12 WD EBV behavior. UPDATE remains REC 2013
/// only and refuses 1.2 announcements. Suite totals and documented divergences
/// are evidence for their tested scope, not blanket language-version support.
pub const CONFORMANCE_VERIFIED_VERSIONS: &[&str] =
    &[SPARQL_VERSION_1_0, SPARQL_VERSION_1_1, SPARQL_VERSION_1_2];

/// [OPUS-4.8] sq-qfcb: `sd:BasicFederatedQuery` — the SPARQL 1.1 Federated Query feature
/// (the `SERVICE` clause). Advertised ONLY when the server is built with the `service`
/// cargo feature (the engine's `SERVICE` evaluation is compiled in); without it a `SERVICE`
/// clause errors at execution, so advertising the feature would be a fiction. See
/// [`Capabilities::federated_query`].
const SD_BASIC_FEDERATED_QUERY: &str =
    "http://www.w3.org/ns/sparql-service-description#BasicFederatedQuery";

/// [OPUS-4.8] sq-yyy3 (follow-up to sq-ntcg/#267): the sparq W3C-PROV-O **data-lineage**
/// capability IRI — advertised via `sd:feature` ONLY when [`Capabilities::provenance`] is set,
/// i.e. when this node genuinely captures + serves PROV-O lineage for the data it derives
/// (`CONSTRUCT` / SPARQL-Update / reasoner-materialization, the `sparq-prov` surface). It is a
/// sparq extension feature (PROV-O lineage is not a standard SPARQL Service Description feature),
/// so it lives under the sparq vocab namespace alongside the `scs:` characteristic-set extension
/// the VoID descriptor already serves. A federation client that reads it knows the source can
/// answer "where did this triple come from?" with standard
/// [W3C PROV-O](https://www.w3.org/TR/prov-o/) — and a client that does not understand the IRI
/// simply ignores it (it is an opaque feature IRI). The flag is FALSE unless a node opts into
/// serving lineage, so the advertisement is never a fiction (the same honesty boundary as
/// `federated_query` / `extension_functions`).
const PROV_LINEAGE_FEATURE_IRI: &str = "http://sparq.dev/ns/prov#lineage";

/// The W3C media-type IRIs (`<https://www.w3.org/ns/formats/...>`) for the result/RDF
/// serialisations the server can RETURN, advertised via `sd:resultFormat`. These mirror the
/// formats [`crate::negotiate`] produces (SELECT/ASK results + CONSTRUCT/DESCRIBE graphs).
const SD_RESULT_FORMATS: &[&str] = &[
    // SPARQL results
    "http://www.w3.org/ns/formats/SPARQL_Results_JSON",
    "http://www.w3.org/ns/formats/SPARQL_Results_XML",
    "http://www.w3.org/ns/formats/SPARQL_Results_CSV",
    "http://www.w3.org/ns/formats/SPARQL_Results_TSV",
    // RDF graph serialisations (CONSTRUCT / DESCRIBE / GSP read)
    "http://www.w3.org/ns/formats/Turtle",
    "http://www.w3.org/ns/formats/N-Triples",
    "http://www.w3.org/ns/formats/RDF_XML",
];

/// [OPUS-4.8] sq-qfcb: the W3C media-type IRIs for the RDF serialisations the server can
/// PARSE on the way IN — the Graph-Store-Protocol write surface and `LOAD` accept these.
/// Advertised via `sd:inputFormat`. The server parses Turtle / N-Triples / RDF-XML (the same
/// three [`crate::negotiate::GraphFormat`]s it serialises), so input and result RDF formats
/// coincide here, but they are kept as a separate list because the SD distinguishes the two
/// and a future asymmetry (e.g. parse-only or write-only formats) must not silently drift.
const SD_INPUT_FORMATS: &[&str] = &[
    "http://www.w3.org/ns/formats/Turtle",
    "http://www.w3.org/ns/formats/N-Triples",
    "http://www.w3.org/ns/formats/RDF_XML",
];

/// A negotiated descriptor response: the serialised body plus its `Content-Type`.
pub struct Descriptor {
    pub content_type: &'static str,
    pub body: String,
}

/// Negotiates the RDF serialisation for a descriptor from the request `Accept` header.
///
/// Reuses the same Turtle / N-Triples / RDF-XML negotiation as the GSP-read + CONSTRUCT
/// surface ([`negotiate_graph`]), but with a Turtle default (the conventional, most readable
/// descriptor serialisation) rather than N-Triples — a bare `curl` of a `.well-known/void`
/// should land on Turtle.
fn negotiate_descriptor(accept: Option<&str>) -> GraphFormat {
    match accept {
        // A non-empty Accept that names at least one concrete media type → honour the
        // client's preference via the shared graph negotiation.
        Some(a) if !a.trim().is_empty() && !is_wildcard_only(a) => negotiate_graph(Some(a)),
        // Empty / absent / wildcard-only Accept → Turtle (the readable default for a human
        // or a generic discovery client hitting the well-known URL).
        _ => GraphFormat::Turtle,
    }
}

/// `true` when every media range in the `Accept` header is the `*/*` catch-all (so the
/// client expressed no concrete preference). Handles q-values and multiple ranges, e.g.
/// `*/*`, `*/*;q=0.8`, `*/* , */*;q=0.1` — all wildcard-only. A single concrete type
/// anywhere (e.g. `text/turtle, */*`) makes it non-wildcard so the client preference wins.
fn is_wildcard_only(accept: &str) -> bool {
    accept
        .split(',')
        .filter(|r| !r.trim().is_empty())
        .all(|range| {
            // Strip parameters (`;q=…`, `;charset=…`) and compare the media range itself.
            range.split(';').next().unwrap_or("").trim() == "*/*"
        })
}

/// Serialises a triple list in the negotiated [`GraphFormat`], reusing the crate's graph
/// serialisers (the same writers the GSP-read path uses), so the descriptor is guaranteed
/// well-formed in whichever syntax is chosen.
fn serialise(triples: &[Triple], fmt: GraphFormat) -> (&'static str, String) {
    let body = match fmt {
        GraphFormat::NTriples => crate::graph::triples_to_ntriples(triples),
        GraphFormat::Turtle => crate::graph::triples_to_turtle(triples),
        GraphFormat::RdfXml => crate::graph::triples_to_rdfxml(triples),
        // [OPUS-4.8] sq-oy1f.1: a descriptor may be requested as JSON-LD too (only matchable
        // when the `jsonld` feature is on; the variant does not exist otherwise).
        #[cfg(feature = "jsonld")]
        GraphFormat::JsonLd => crate::graph::triples_to_jsonld(triples),
    };
    (fmt.content_type(), body)
}

/// Parses an N-Triples document (the output of [`Introspection::to_void`] / [`sd_ntriples`])
/// into an [`oxrdf::Triple`] vector so it can be re-serialised in the negotiated syntax.
///
/// The inputs are machine-generated, well-formed N-Triples (oxrdf `Display` per term), so a
/// parse error here is a programming error, not a client-facing one — we surface it as an
/// internal error rather than silently dropping triples.
fn parse_ntriples(nt: &str) -> Result<Vec<Triple>, String> {
    let mut out = Vec::new();
    for r in oxttl::NTriplesParser::new().for_slice(nt.as_bytes()) {
        out.push(r.map_err(|e| format!("internal: malformed descriptor N-Triples: {e}"))?);
    }
    Ok(out)
}

/// Builds the VoID descriptor for `graph`, named `dataset_iri`, serialised per `accept`.
///
/// `dataset_iri` is the IRI that names the `void:Dataset` (conventionally the dataset's URL,
/// e.g. `https://host/.well-known/void#dataset`). Generation delegates to
/// [`Introspection::to_void_with_cs`] — the standard VoID counts + class/property partitions,
/// **plus** the characteristic-set source statistics (the sparq `scs:` extension; see
/// [`Introspection::to_void_with_cs`] / sq-mr32, federation A3/Z2). The CS stats ride the
/// same opt-in `federation-descriptors` gating as the rest of this module: a federation
/// client polling `/.well-known/void` on a CS-aware sparq node gets per-entity-type predicate
/// co-occurrence + multiplicity for sharp star/multi-join source selection, while a
/// VoID-only client reads the unchanged standard partitions and ignores the rest. The only
/// work here is re-serialising into the negotiated syntax.
pub fn void_descriptor(
    graph: &Graph,
    dataset_iri: &str,
    accept: Option<&str>,
) -> Result<Descriptor, String> {
    let nt = Introspection::build(graph).to_void_with_cs(dataset_iri);
    let triples = parse_ntriples(&nt)?;
    let fmt = negotiate_descriptor(accept);
    let (content_type, body) = serialise(&triples, fmt);
    Ok(Descriptor { content_type, body })
}

/// [OPUS-4.8] sq-qfcb: the server's ACTUAL, build-and-config-determined capabilities, so the
/// Service Description advertises exactly what this binary can do — never a hard-coded fiction.
///
/// Every field reflects a genuine capability the running server has:
///
///   * `update` — whether the server will EXECUTE a SPARQL Update. The protocol write path is
///     always compiled in, but the operator can make the surface effectively read-only (the
///     [`auth_token`](crate::ServerConfig::auth_token) write gate). We advertise
///     `sd:SPARQL11Update` only when an anonymous client could actually run an update — i.e.
///     no write-token is configured. When a write-token gates updates, an unauthenticated SD
///     reader cannot use Update, so advertising it would over-promise; the operator who holds
///     the token knows it is available.
///   * `federated_query` — `true` only with the `service` cargo feature (engine `SERVICE`
///     evaluation compiled in). Advertised as `sd:feature sd:BasicFederatedQuery`.
///   * `extension_functions` — the IRIs of the extension functions ACTUALLY registered
///     (the `geof:` GeoSPARQL set with the `geo` feature; empty otherwise), advertised one
///     `sd:extensionFunction` each. Sourced from the live registry's
///     [`iris`](sparq_engine::FunctionRegistry::iris) so it can never drift from what runs.
#[derive(Debug, Clone, Default)]
pub struct Capabilities {
    /// Advertise `sd:SPARQL11Update` (an anonymous client can run an Update).
    pub update: bool,
    /// Advertise `sd:feature sd:BasicFederatedQuery` (the `SERVICE` clause is compiled in).
    pub federated_query: bool,
    /// `sd:extensionFunction` IRIs — exactly the functions the engine has registered.
    pub extension_functions: Vec<String>,
    /// [OPUS-4.8] sq-yyy3: advertise `sd:feature <http://sparq.dev/ns/prov#lineage>` — this node
    /// captures + serves W3C PROV-O data-lineage for the data it derives (the `sparq-prov`
    /// surface). FALSE unless the node genuinely serves lineage, so the advertisement is never a
    /// fiction. The advertised feature IRI is `<http://sparq.dev/ns/prov#lineage>`.
    pub provenance: bool,
    /// [OPUS-4.8] sq-2msb (gh-917): the `sparql:version-*` IRIs to advertise via
    /// `sd:supportedVersion` — the SPARQL language VERSIONS this build conformance-verifies.
    ///
    /// HONESTY GATE (load-bearing): there is NO `sparql12`/`rdf12` cargo feature — SPARQL 1.2
    /// evaluation (triple terms, `dir`-tagged literals, the version functions) is compiled into
    /// the BASE `sparq-engine` and always on, so this is NOT keyed off a `cfg!(feature = …)`.
    /// Instead it is keyed off the engine's DOCUMENTED, conformance-verified state: this list
    /// must name exactly the versions whose official W3C suites this build PASSES, never an
    /// aspiration. A blanket `version-1.2` may be advertised ONLY while the full `sparql12`
    /// suite is green (it is — see `conformance-report.md`); were any 1.2 group to fall to a
    /// partial pass, the honest move is to drop to `version-1.2-basic` or omit 1.2 here, NOT to
    /// keep over-promising. The caller ([`service_capabilities`](crate::descriptors)) sources it
    /// from a single documented constant so the gate stays visible in one place.
    ///
    /// EMPTY by [`Default`] (the same fail-closed default as every other capability), so a unit
    /// test that builds a bare profile advertises no version unless it opts in. The HTTP layer
    /// populates the real, conformance-verified list.
    pub sparql_versions: Vec<String>,
}

/// [OPUS-4.8] sq-optl: one named graph of the served dataset, for the Service Description's
/// `sd:namedGraph` enumeration. `name` is the graph's IRI (the value that may be used in a
/// `FROM NAMED` / `GRAPH <name>` clause — `sd:name`); `triples` is its triple count, surfaced
/// as a `void:triples` on the graph's `sd:Graph` description so a federation client can size a
/// per-graph query without a separate count.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct NamedGraphDesc {
    /// The graph's name IRI — `sd:name`, usable in `FROM NAMED` / `GRAPH <name>`.
    pub name: String,
    /// The graph's triple count — `void:triples` on its `sd:Graph` description.
    pub triples: usize,
}

/// [OPUS-4.8] sq-optl: enumerate the served dataset's named graphs for the Service Description.
///
/// Returns one [`NamedGraphDesc`] per named graph whose name is an IRI, SORTED by name so the
/// emitted SD is deterministic (independent of insertion / storage order). Blank-node and
/// literal graph names are skipped: `sd:name` ranges over an IRI ("the name by which it may be
/// referenced in a FROM/FROM NAMED clause", SD §5.5), and a `FROM NAMED` clause can only name an
/// IRI — a blank-node-named graph is not referenceable that way, so advertising it would be a
/// fiction. (sparq's RDF-1.2 dataset model can carry a blank-node graph name, but it cannot be
/// the target of `FROM NAMED`.)
///
/// Reuses the existing public [`Graph::for_named_graphs_with_prefix`] enumeration with the
/// empty prefix (matches every named graph) rather than reaching into private state — the same
/// read-only snapshot scan the VoID descriptor already performs.
pub fn named_graph_descriptions(graph: &Graph) -> Vec<NamedGraphDesc> {
    let mut out = Vec::new();
    graph.for_named_graphs_with_prefix("", |name, sub| {
        // Only IRI-named graphs are `FROM NAMED`-referenceable, so only they get an `sd:name`.
        if let Term::NamedNode(n) = name {
            out.push(NamedGraphDesc {
                name: n.as_str().to_string(),
                triples: sub.len(),
            });
        }
    });
    out.sort_by(|a, b| a.name.cmp(&b.name));
    out
}

/// Builds the SPARQL Service Description for the endpoint, serialised per `accept`.
///
/// * `service_iri` names the `sd:Service` (conventionally the endpoint URL, e.g.
///   `https://host/sparql`).
/// * `endpoint_iri` is the `sd:endpoint` value (the same endpoint URL).
/// * `dataset_iri` is the `void:Dataset` the default graph exposes — linked both as the
///   `sd:defaultDataset`'s `sd:defaultGraph` (typed as a `void:Dataset`) and via
///   `dcterms:source` to the VoID document, so a federation client can discover counts from
///   one descriptor and the capability profile from the other.
/// * `caps` are the server's ACTUAL capabilities (see [`Capabilities`]) — every advertised
///   feature/language/function reflects something this binary genuinely supports.
/// * `named_graphs` are the served dataset's named graphs ([`named_graph_descriptions`]) — each
///   is advertised as an `sd:namedGraph` of the default dataset, an `sd:NamedGraph` with its
///   `sd:name` (the `FROM NAMED`-referenceable IRI) and an `sd:graph` `sd:Graph` carrying the
///   per-graph `void:triples` count. An empty slice (no named graphs) emits nothing extra.
///
/// The SD advertises: the endpoint, `sd:Service` typing, the supported query language(s) — both
/// the legacy `sd:SPARQL11Query` and the SPARQL-1.2-SD version-agnostic `sd:SPARQLQuery` (plus
/// `sd:SPARQL11Update`/`sd:SPARQLUpdate` when [`Capabilities::update`]) — the supported SPARQL
/// language VERSIONS via `sd:supportedVersion` ([`Capabilities::sparql_versions`], sq-2msb), the
/// supported result + input RDF formats (`SD_RESULT_FORMATS` / `SD_INPUT_FORMATS`), the
/// federated-query feature when compiled in, the registered extension functions, and the default
/// dataset — its default graph (linked to the VoID dataset IRI) plus an `sd:namedGraph`
/// enumeration of every IRI-named graph.
pub fn service_description(
    service_iri: &str,
    endpoint_iri: &str,
    dataset_iri: &str,
    caps: &Capabilities,
    named_graphs: &[NamedGraphDesc],
    accept: Option<&str>,
) -> Result<Descriptor, String> {
    let nt = sd_ntriples(service_iri, endpoint_iri, dataset_iri, caps, named_graphs);
    let triples = parse_ntriples(&nt)?;
    let fmt = negotiate_descriptor(accept);
    let (content_type, body) = serialise(&triples, fmt);
    Ok(Descriptor { content_type, body })
}

/// Renders the Service Description as N-Triples (the syntactic subset every serialiser can
/// re-emit). Hand-written rather than via a builder dependency — the SD is a small fixed
/// shape, so a few `writeln!`s keep it dependency-free and auditable.
fn sd_ntriples(
    service_iri: &str,
    endpoint_iri: &str,
    dataset_iri: &str,
    caps: &Capabilities,
    named_graphs: &[NamedGraphDesc],
) -> String {
    use std::fmt::Write as _;
    let sd = |local: &str| format!("{SD_NS}{local}");
    // oxrdf NamedNode Display is N-Triples-safe (escapes/brackets correctly). Use the
    // CHECKED constructor: `service_iri`/`endpoint_iri`/`dataset_iri` are ultimately
    // derived from the request `Host` header, and although the HTTP layer now validates
    // the base IRI, we defend in depth here so an invalid IRI can never emit malformed
    // N-Triples (which would fail re-parse → a 500). An invalid value falls back to a
    // fixed safe IRI rather than corrupting the document. The same checked constructor
    // guards an extension-function IRI (sourced from the live registry, so always valid,
    // but defended in depth all the same).
    const SAFE_IRI: &str = "http://localhost/invalid-iri";
    let iri = |s: &str| {
        oxrdf::NamedNode::new(s)
            .unwrap_or_else(|_| oxrdf::NamedNode::new_unchecked(SAFE_IRI))
            .to_string()
    };

    let svc = iri(service_iri);
    let mut out = String::new();

    // ---- The sd:Service: typing + endpoint.
    let _ = writeln!(out, "{svc} <{RDF_TYPE}> <{}> .", sd("Service"));
    let _ = writeln!(out, "{svc} <{}> {} .", sd("endpoint"), iri(endpoint_iri));

    // ---- Supported query language(s). SPARQL 1.1 Query is always supported; SPARQL 1.1
    // Update is advertised only when an anonymous client can actually run one (no write gate).
    // [OPUS-4.8] sq-2msb: we advertise BOTH the legacy "language+version" `sd:SPARQL11Query`/
    // `sd:SPARQL11Update` terms AND the SPARQL 1.2 SD version-AGNOSTIC `sd:SPARQLQuery`/
    // `sd:SPARQLUpdate` terms — a 1.1-only client recognises the legacy ones, a 1.2-aware client
    // recognises the version-agnostic ones and reads the precise version off `sd:supportedVersion`
    // (below). Both are honest: Query is always evaluable, Update follows the same anonymous-write
    // gate as before.
    let _ = writeln!(
        out,
        "{svc} <{}> {} .",
        sd("supportedLanguage"),
        iri(SD_SPARQL11_QUERY)
    );
    let _ = writeln!(
        out,
        "{svc} <{}> {} .",
        sd("supportedLanguage"),
        iri(SD_SPARQL_QUERY)
    );
    if caps.update {
        let _ = writeln!(
            out,
            "{svc} <{}> {} .",
            sd("supportedLanguage"),
            iri(SD_SPARQL11_UPDATE)
        );
        let _ = writeln!(
            out,
            "{svc} <{}> {} .",
            sd("supportedLanguage"),
            iri(SD_SPARQL_UPDATE)
        );
    }

    // ---- [OPUS-4.8] sq-2msb (gh-917): supported SPARQL language VERSIONS. SPARQL 1.2 SD moves
    // version negotiation off `sd:Language` onto `sd:supportedVersion <sparql:version-X>`. We
    // emit EXACTLY the versions this build conformance-verifies (`caps.sparql_versions`, sourced
    // from the documented constant in `service_capabilities`), so a 1.2-aware federation client
    // can discover triple-term / dir-lang support without probing. The list is pre-built (already
    // deterministic) and EMPTY in the default `Capabilities`, so a profile that opts out of the
    // version posture emits nothing here (no over-promise, byte-stable).
    for v in &caps.sparql_versions {
        let _ = writeln!(out, "{svc} <{}> {} .", sd("supportedVersion"), iri(v));
    }

    // ---- Result formats the server can RETURN, and input RDF formats it can PARSE.
    for f in SD_RESULT_FORMATS {
        let _ = writeln!(out, "{svc} <{}> {} .", sd("resultFormat"), iri(f));
    }
    for f in SD_INPUT_FORMATS {
        let _ = writeln!(out, "{svc} <{}> {} .", sd("inputFormat"), iri(f));
    }

    // ---- sd:feature — only genuinely-compiled features. Federated query (the SERVICE
    // clause) is the one this server gates on a cargo feature; advertise it only when on.
    if caps.federated_query {
        let _ = writeln!(
            out,
            "{svc} <{}> {} .",
            sd("feature"),
            iri(SD_BASIC_FEDERATED_QUERY)
        );
    }

    // [OPUS-4.8] sq-yyy3: the sparq PROV-O data-lineage extension feature — advertised only when
    // this node genuinely captures + serves lineage (the `sparq-prov` surface). Like
    // BasicFederatedQuery it is a genuine, build/config-determined capability, never a fiction.
    if caps.provenance {
        let _ = writeln!(
            out,
            "{svc} <{}> {} .",
            sd("feature"),
            iri(PROV_LINEAGE_FEATURE_IRI)
        );
    }

    // ---- sd:extensionFunction — EXACTLY the functions the engine has registered. Sorted so
    // the document is deterministic regardless of the registry's hash-map iteration order.
    let mut fns: Vec<&str> = caps
        .extension_functions
        .iter()
        .map(String::as_str)
        .collect();
    fns.sort_unstable();
    for f in fns {
        let _ = writeln!(out, "{svc} <{}> {} .", sd("extensionFunction"), iri(f));
    }

    // ---- The default dataset (a blank node) → default graph → the VoID dataset.
    let ds = "_:dataset";
    let g = "_:defaultGraph";
    let _ = writeln!(out, "{svc} <{}> {ds} .", sd("defaultDataset"));
    let _ = writeln!(out, "{ds} <{RDF_TYPE}> <{}> .", sd("Dataset"));
    let _ = writeln!(out, "{ds} <{}> {g} .", sd("defaultGraph"));
    let _ = writeln!(out, "{g} <{RDF_TYPE}> <{}> .", sd("Graph"));
    // Also type the default graph as a void:Dataset (the descriptor that carries counts),
    // and add a dcterms:source pointer from the service to the VoID document.
    let _ = writeln!(out, "{g} <{RDF_TYPE}> <{VOID_NS}Dataset> .");
    let _ = writeln!(out, "{svc} <{DCTERMS_NS}source> {} .", iri(dataset_iri));

    // ---- [OPUS-4.8] sq-optl: the dataset's NAMED graphs. `sd:Dataset` is a subclass of
    // `sd:GraphCollection`, so its named graphs are linked with `sd:namedGraph`, each an
    // `sd:NamedGraph` carrying its `sd:name` (the `FROM NAMED`-referenceable IRI) and an
    // `sd:graph` `sd:Graph` description with the per-graph `void:triples` count. `named_graphs`
    // is pre-sorted + IRI-only (see `named_graph_descriptions`), so the output is deterministic
    // and every `sd:name` is genuinely referenceable. Fresh blank-node labels per entry
    // (`_:ngN` / `_:ngGN`) keep the N-Triples well-formed for the re-parse + re-serialise.
    for (i, ng) in named_graphs.iter().enumerate() {
        let ng_node = format!("_:ng{i}");
        let ng_graph = format!("_:ngG{i}");
        let _ = writeln!(out, "{ds} <{}> {ng_node} .", sd("namedGraph"));
        let _ = writeln!(out, "{ng_node} <{RDF_TYPE}> <{}> .", sd("NamedGraph"));
        let _ = writeln!(out, "{ng_node} <{}> {} .", sd("name"), iri(&ng.name));
        let _ = writeln!(out, "{ng_node} <{}> {ng_graph} .", sd("graph"));
        let _ = writeln!(out, "{ng_graph} <{RDF_TYPE}> <{}> .", sd("Graph"));
        // The per-graph triple count, as a void:triples xsd:integer literal.
        let _ = writeln!(
            out,
            "{ng_graph} <{VOID_NS}triples> \"{}\"^^<http://www.w3.org/2001/XMLSchema#integer> .",
            ng.triples
        );
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;

    fn graph() -> Graph {
        Graph::load_str(
            "@prefix ex: <http://ex/> .\n\
             ex:alice a ex:Person ; ex:knows ex:bob .\n\
             ex:bob a ex:Person .\n",
            "turtle",
        )
        .unwrap()
    }

    #[test]
    fn void_turtle_carries_triples_count() {
        let d = void_descriptor(
            &graph(),
            "http://host/.well-known/void#dataset",
            Some("text/turtle"),
        )
        .unwrap();
        assert_eq!(d.content_type, "text/turtle; charset=utf-8");
        assert!(
            d.body.contains("triples"),
            "VoID must carry void:triples: {}",
            d.body
        );
        // The raw VoID N-Triples carries the void:triples predicate.
        let nt = Introspection::build(&graph()).to_void("http://host/.well-known/void#dataset");
        assert!(nt.contains("<http://rdfs.org/ns/void#triples>"));
    }

    #[test]
    fn void_descriptor_carries_characteristic_set_stats() {
        // [OPUS-4.8] sq-mr32 (federation A3/Z2): the served VoID must now also carry the
        // characteristic-set source statistics (sparq `scs:` extension), in valid RDF.
        // N-Triples first (exact predicate IRIs), then Turtle (must re-parse).
        let nt = void_descriptor(
            &graph(),
            "http://host/.well-known/void#dataset",
            Some("application/n-triples"),
        )
        .unwrap();
        let b = &nt.body;
        // Standard VoID is still present (CS rides ALONGSIDE, never replaces it).
        assert!(b.contains("<http://rdfs.org/ns/void#Dataset>"), "{b}");
        // Dataset links to characteristic sets + carries the EXACT distinct-set count.
        assert!(
            b.contains("<http://sparq.dev/ns/cs#characteristicSet>"),
            "served VoID must link the dataset to characteristic sets: {b}"
        );
        assert!(
            b.contains("<http://sparq.dev/ns/cs#distinctCharacteristicSets>"),
            "served VoID must carry the distinct-set count: {b}"
        );
        // A CS node: typed, with subjects + per-predicate stat nodes (property + triples
        // + avg multiplicity).
        assert!(
            b.contains("<http://sparq.dev/ns/cs#CharacteristicSet>"),
            "{b}"
        );
        assert!(b.contains("<http://sparq.dev/ns/cs#subjects>"), "{b}");
        assert!(b.contains("<http://sparq.dev/ns/cs#predicateStat>"), "{b}");
        assert!(
            b.contains("<http://sparq.dev/ns/cs#avgMultiplicity>"),
            "{b}"
        );
        // Per-predicate stat reuses void:property/void:triples and names a real predicate.
        assert!(b.contains("<http://rdfs.org/ns/void#property>"), "{b}");
        assert!(
            b.contains("<http://ex/knows>"),
            "CS stat must name the predicate: {b}"
        );

        // Turtle serialisation of the same document must be well-formed RDF and still
        // carry the CS extension namespace.
        let tt = void_descriptor(&graph(), "http://host/ds", Some("text/turtle")).unwrap();
        assert_eq!(tt.content_type, "text/turtle; charset=utf-8");
        let mut n = 0usize;
        for r in oxttl::TurtleParser::new().for_slice(tt.body.as_bytes()) {
            r.expect("VoID+CS Turtle must be valid RDF");
            n += 1;
        }
        assert!(n >= 10, "VoID+CS should have many triples, got {n}");
        assert!(
            tt.body.contains("sparq.dev/ns/cs#"),
            "Turtle VoID must carry the CS extension vocab: {}",
            tt.body
        );
    }

    #[test]
    fn void_ntriples_negotiated() {
        let d = void_descriptor(&graph(), "http://host/ds", Some("application/n-triples")).unwrap();
        assert_eq!(d.content_type, "application/n-triples; charset=utf-8");
        assert!(d.body.contains("<http://rdfs.org/ns/void#Dataset>"));
    }

    #[test]
    fn void_default_is_turtle() {
        // No Accept (None), empty, and any WILDCARD-ONLY Accept (incl. q-values and
        // multiple wildcard ranges) all default to Turtle — not just the literal "*/*".
        for accept in [
            None,
            Some("*/*"),
            Some(""),
            Some("*/*;q=0.8"),
            Some(" */* , */*;q=0.1 "),
        ] {
            let d = void_descriptor(&graph(), "http://host/ds", accept).unwrap();
            assert_eq!(
                d.content_type, "text/turtle; charset=utf-8",
                "accept={accept:?}"
            );
        }
        // A concrete type alongside a wildcard still honours the concrete preference.
        let d = void_descriptor(
            &graph(),
            "http://host/ds",
            Some("application/n-triples, */*"),
        )
        .unwrap();
        assert_eq!(d.content_type, "application/n-triples; charset=utf-8");
    }

    /// A capability profile for tests: read-only, no federation, no extension functions.
    fn read_only_caps() -> Capabilities {
        Capabilities::default()
    }

    #[test]
    fn sd_invalid_iri_falls_back_not_500() {
        // A bad (header-derived) IRI must not produce malformed N-Triples that fail the
        // re-parse → a 500. The checked constructor swaps it for a safe IRI instead, so
        // the descriptor still builds and re-parses cleanly.
        let d = service_description(
            "http://bad host/sparql", // space ⇒ invalid IRI
            "http://bad host/sparql",
            "http://host/ds",
            &read_only_caps(),
            &[],
            Some("application/n-triples"),
        )
        .expect("invalid Host-derived IRI must fall back, not error/500");
        assert_eq!(d.content_type, "application/n-triples; charset=utf-8");
        assert!(
            d.body.contains("/invalid-iri"),
            "invalid IRI should be replaced by the safe fallback: {}",
            d.body
        );
    }

    #[test]
    fn sd_advertises_endpoint_languages_formats() {
        let d = service_description(
            "http://host/sparql",
            "http://host/sparql",
            "http://host/.well-known/void#dataset",
            &read_only_caps(),
            &[],
            Some("application/n-triples"),
        )
        .unwrap();
        assert_eq!(d.content_type, "application/n-triples; charset=utf-8");
        let b = &d.body;
        // sd:Service typing + endpoint.
        assert!(b.contains("<http://www.w3.org/ns/sparql-service-description#Service>"));
        assert!(b.contains("<http://www.w3.org/ns/sparql-service-description#endpoint>"));
        assert!(b.contains("<http://host/sparql>"));
        // supportedLanguage SPARQL11Query (always).
        assert!(b.contains("SPARQL11Query"));
        // result formats AND input formats.
        assert!(b.contains("SPARQL_Results_JSON"));
        assert!(b.contains("/formats/Turtle"));
        assert!(b.contains("<http://www.w3.org/ns/sparql-service-description#inputFormat>"));
        // defaultDataset link + dcterms:source to the VoID document.
        assert!(b.contains("#defaultDataset"));
        assert!(b.contains("<http://purl.org/dc/terms/source>"));
        assert!(b.contains("<http://host/.well-known/void#dataset>"));
    }

    #[test]
    fn sd_update_language_is_conditional() {
        // [OPUS-4.8] sq-qfcb: SPARQL11Update is advertised only when the server reports the
        // update capability — never when an anonymous client cannot run an update.
        let read_only = service_description(
            "http://host/sparql",
            "http://host/sparql",
            "http://host/ds",
            &read_only_caps(),
            &[],
            Some("application/n-triples"),
        )
        .unwrap();
        assert!(
            !read_only.body.contains("SPARQL11Update"),
            "read-only profile must NOT advertise SPARQL11Update: {}",
            read_only.body
        );

        let writable = service_description(
            "http://host/sparql",
            "http://host/sparql",
            "http://host/ds",
            &Capabilities {
                update: true,
                ..Capabilities::default()
            },
            &[],
            Some("application/n-triples"),
        )
        .unwrap();
        assert!(
            writable.body.contains("SPARQL11Update"),
            "writable profile must advertise SPARQL11Update: {}",
            writable.body
        );
    }

    #[test]
    fn sd_federated_query_and_extension_functions_only_when_present() {
        // [OPUS-4.8] sq-qfcb: BasicFederatedQuery and extension functions are advertised
        // ONLY when the capability is genuinely present — honesty, not aspiration.
        let absent = service_description(
            "http://host/sparql",
            "http://host/sparql",
            "http://host/ds",
            &read_only_caps(),
            &[],
            Some("application/n-triples"),
        )
        .unwrap();
        assert!(
            !absent.body.contains("BasicFederatedQuery"),
            "{}",
            absent.body
        );
        assert!(
            !absent.body.contains("extensionFunction"),
            "{}",
            absent.body
        );

        let present = service_description(
            "http://host/sparql",
            "http://host/sparql",
            "http://host/ds",
            &Capabilities {
                update: false,
                federated_query: true,
                extension_functions: vec![
                    "http://www.opengis.net/def/function/geosparql/distance".to_string()
                ],
                ..Capabilities::default()
            },
            &[],
            Some("application/n-triples"),
        )
        .unwrap();
        assert!(
            present
                .body
                .contains("<http://www.w3.org/ns/sparql-service-description#BasicFederatedQuery>"),
            "{}",
            present.body
        );
        assert!(
            present
                .body
                .contains("<http://www.w3.org/ns/sparql-service-description#extensionFunction>"),
            "{}",
            present.body
        );
        assert!(
            present
                .body
                .contains("<http://www.opengis.net/def/function/geosparql/distance>"),
            "{}",
            present.body
        );
    }

    #[test]
    fn sd_provenance_feature_only_when_present() {
        // [OPUS-4.8] sq-yyy3: the PROV-O lineage feature IRI is advertised ONLY when the node
        // reports the provenance capability — honesty, not aspiration (like BasicFederatedQuery).
        let absent = service_description(
            "http://host/sparql",
            "http://host/sparql",
            "http://host/ds",
            &read_only_caps(),
            &[],
            Some("application/n-triples"),
        )
        .unwrap();
        assert!(
            !absent.body.contains("sparq.dev/ns/prov#lineage"),
            "a node that does not serve lineage must NOT advertise the PROV-O feature: {}",
            absent.body
        );

        let present = service_description(
            "http://host/sparql",
            "http://host/sparql",
            "http://host/ds",
            &Capabilities {
                provenance: true,
                ..Capabilities::default()
            },
            &[],
            Some("application/n-triples"),
        )
        .unwrap();
        // Emitted as a standard sd:feature whose object is the sparq PROV-O lineage IRI.
        assert!(
            present.body.contains(
                "<http://www.w3.org/ns/sparql-service-description#feature> \
                 <http://sparq.dev/ns/prov#lineage>"
            ),
            "a lineage-serving node must advertise sd:feature <…/prov#lineage>: {}",
            present.body
        );
        // Re-parses as valid N-Triples (the extra feature triple is well-formed).
        for r in oxttl::NTriplesParser::new().for_slice(present.body.as_bytes()) {
            r.expect("SD with the PROV-O feature must be valid N-Triples");
        }
    }

    #[test]
    fn sd_supported_version_only_when_set() {
        // [OPUS-4.8] sq-2msb (gh-917): the load-bearing invariant — `sd:supportedVersion` is
        // emitted IFF `Capabilities::sparql_versions` is non-empty (the honesty gate). The
        // version-agnostic SPARQL 1.2 language term `sd:SPARQLQuery` is always present (Query is
        // always evaluable); the legacy `sd:SPARQL11Query` stays too (1.1-client back-compat).
        let absent = service_description(
            "http://host/sparql",
            "http://host/sparql",
            "http://host/ds",
            &read_only_caps(), // default ⇒ empty sparql_versions
            &[],
            Some("application/n-triples"),
        )
        .unwrap();
        assert!(
            !absent.body.contains("supportedVersion"),
            "no sparql_versions ⇒ NO sd:supportedVersion triple: {}",
            absent.body
        );
        assert!(
            !absent.body.contains("/ns/sparql#version-"),
            "no sparql_versions ⇒ NO sparql:version-* IRI: {}",
            absent.body
        );
        // The version-agnostic 1.2 language term + the legacy 1.1 term are BOTH advertised.
        assert!(
            absent
                .body
                .contains("<http://www.w3.org/ns/sparql-service-description#SPARQLQuery>"),
            "the 1.2-SD version-agnostic sd:SPARQLQuery must be advertised: {}",
            absent.body
        );
        assert!(
            absent
                .body
                .contains("<http://www.w3.org/ns/sparql-service-description#SPARQL11Query>"),
            "the legacy sd:SPARQL11Query must still be advertised (1.1 back-compat): {}",
            absent.body
        );

        // With the conformance-verified versions set, each `sparql:version-*` IRI is emitted via
        // `sd:supportedVersion`, and the document re-parses cleanly.
        let present = service_description(
            "http://host/sparql",
            "http://host/sparql",
            "http://host/ds",
            &Capabilities {
                sparql_versions: CONFORMANCE_VERIFIED_VERSIONS
                    .iter()
                    .map(|v| (*v).to_string())
                    .collect(),
                ..Capabilities::default()
            },
            &[],
            Some("application/n-triples"),
        )
        .unwrap();
        let b = &present.body;
        let sv = "<http://www.w3.org/ns/sparql-service-description#supportedVersion>";
        for ver in CONFORMANCE_VERIFIED_VERSIONS {
            assert!(
                b.contains(&format!("{sv} <{ver}>")),
                "must advertise sd:supportedVersion <{ver}>: {b}"
            );
        }
        // [GPT-6] Preserve the existing label serialization, independently of
        // the explicitly scoped execution contract above.
        assert!(
            b.contains("<http://www.w3.org/ns/sparql#version-1.2>"),
            "existing version-1.2 label must be serialized: {b}"
        );
        assert!(
            !b.contains("version-1.2-basic"),
            "existing label set does not include version-1.2-basic: {b}"
        );
        for r in oxttl::NTriplesParser::new().for_slice(b.as_bytes()) {
            r.expect("SD with sd:supportedVersion must be valid N-Triples");
        }
    }

    #[test]
    fn sd_update_emits_version_agnostic_language_term() {
        // [OPUS-4.8] sq-2msb: when anonymous Update is possible, BOTH the legacy sd:SPARQL11Update
        // and the 1.2-SD version-agnostic sd:SPARQLUpdate are advertised; when it is not, NEITHER
        // is (the same anonymous-write gate as before, extended to the new term).
        let writable = service_description(
            "http://host/sparql",
            "http://host/sparql",
            "http://host/ds",
            &Capabilities {
                update: true,
                ..Capabilities::default()
            },
            &[],
            Some("application/n-triples"),
        )
        .unwrap();
        assert!(
            writable
                .body
                .contains("<http://www.w3.org/ns/sparql-service-description#SPARQLUpdate>"),
            "writable profile must advertise the version-agnostic sd:SPARQLUpdate: {}",
            writable.body
        );
        assert!(
            writable.body.contains("SPARQL11Update"),
            "writable profile must still advertise legacy sd:SPARQL11Update: {}",
            writable.body
        );

        let read_only = service_description(
            "http://host/sparql",
            "http://host/sparql",
            "http://host/ds",
            &read_only_caps(),
            &[],
            Some("application/n-triples"),
        )
        .unwrap();
        assert!(
            !read_only.body.contains("SPARQLUpdate") && !read_only.body.contains("SPARQL11Update"),
            "read-only profile must advertise NO Update language term: {}",
            read_only.body
        );
    }

    #[test]
    fn sd_reparses_as_turtle() {
        // Turtle serialisation must be well-formed (round-trips through oxttl). Use the
        // richest profile so every advertised triple shape is exercised.
        let d = service_description(
            "http://host/sparql",
            "http://host/sparql",
            "http://host/ds",
            &Capabilities {
                update: true,
                federated_query: true,
                extension_functions: vec![
                    "http://www.opengis.net/def/function/geosparql/distance".to_string(),
                    "http://www.opengis.net/def/function/geosparql/buffer".to_string(),
                ],
                // [OPUS-4.8] sq-yyy3: richest profile also advertises PROV-O lineage, so the
                // extra sd:feature triple is exercised through the Turtle re-parse too.
                provenance: true,
                // [OPUS-4.8] sq-2msb: richest profile also advertises the full version posture, so
                // the sd:supportedVersion triple shape is exercised through the Turtle re-parse.
                sparql_versions: CONFORMANCE_VERIFIED_VERSIONS
                    .iter()
                    .map(|v| (*v).to_string())
                    .collect(),
            },
            // [OPUS-4.8] sq-optl: include named graphs so the namedGraph triple shape
            // (blank-node NamedGraph + Graph + void:triples literal) is exercised in Turtle too.
            &[
                NamedGraphDesc {
                    name: "http://host/g/people".to_string(),
                    triples: 3,
                },
                NamedGraphDesc {
                    name: "http://host/g/orgs".to_string(),
                    triples: 0,
                },
            ],
            Some("text/turtle"),
        )
        .unwrap();
        assert_eq!(d.content_type, "text/turtle; charset=utf-8");
        let mut n = 0;
        for r in oxttl::TurtleParser::new().for_slice(d.body.as_bytes()) {
            r.expect("SD Turtle must be valid");
            n += 1;
        }
        assert!(n >= 3, "SD should have several triples, got {n}");
    }

    /// [OPUS-4.8] sq-optl: a graph with two IRI-named graphs, for the enumeration tests. Uses
    /// `load_dataset` (NOT `load_str`) — only the dataset loader preserves named graphs as
    /// separate sub-graphs; `load_str` collapses every quad into the default graph.
    fn graph_with_named() -> Graph {
        Graph::load_dataset(
            "@prefix ex: <http://ex/> .\n\
             ex:a a ex:Person .\n\
             ex:b a ex:Person .\n\
             ex:beta { ex:x ex:p ex:y . ex:y ex:p ex:z . }\n\
             ex:alpha { ex:s ex:p ex:o . }\n",
            "trig",
        )
        .unwrap()
    }

    #[test]
    fn named_graph_descriptions_are_sorted_iri_only_with_counts() {
        let descs = named_graph_descriptions(&graph_with_named());
        // Two IRI-named graphs, returned SORTED by name (alpha before beta) regardless of the
        // TriG document order (beta is written first above).
        assert_eq!(
            descs,
            vec![
                NamedGraphDesc {
                    name: "http://ex/alpha".to_string(),
                    triples: 1,
                },
                NamedGraphDesc {
                    name: "http://ex/beta".to_string(),
                    triples: 2,
                },
            ],
            "named graphs must be IRI-only, sorted, with per-graph triple counts"
        );
    }

    #[test]
    fn sd_enumerates_named_graphs() {
        // The default dataset must advertise each named graph as an sd:namedGraph →
        // sd:NamedGraph with its sd:name (the FROM NAMED IRI), an sd:graph sd:Graph, and the
        // per-graph void:triples count.
        let descs = named_graph_descriptions(&graph_with_named());
        let d = service_description(
            "http://host/sparql",
            "http://host/sparql",
            "http://host/ds",
            &read_only_caps(),
            &descs,
            Some("application/n-triples"),
        )
        .unwrap();
        let b = &d.body;
        let sd = |l: &str| format!("<http://www.w3.org/ns/sparql-service-description#{l}>");
        // The dataset links each named graph via sd:namedGraph, typed sd:NamedGraph.
        assert!(
            b.contains(&sd("namedGraph")),
            "must link sd:namedGraph: {b}"
        );
        assert!(
            b.contains(&sd("NamedGraph")),
            "must type sd:NamedGraph: {b}"
        );
        // Each carries an sd:name naming the real graph IRI (FROM NAMED-referenceable).
        assert!(b.contains(&sd("name")), "must carry sd:name: {b}");
        assert!(
            b.contains("<http://ex/alpha>"),
            "must name the graph IRI: {b}"
        );
        assert!(
            b.contains("<http://ex/beta>"),
            "must name the graph IRI: {b}"
        );
        // Each links an sd:graph sd:Graph carrying a void:triples count (alpha=1, beta=2).
        assert!(b.contains(&sd("graph")), "must link sd:graph: {b}");
        assert!(
            b.contains("<http://rdfs.org/ns/void#triples>"),
            "per-graph void:triples: {b}"
        );
        assert!(
            b.contains("\"1\"^^<http://www.w3.org/2001/XMLSchema#integer>")
                && b.contains("\"2\"^^<http://www.w3.org/2001/XMLSchema#integer>"),
            "per-graph triple counts (1 and 2): {b}"
        );
        // Re-parses as valid N-Triples (the blank-node fan-out is well-formed).
        let mut n = 0;
        for r in oxttl::NTriplesParser::new().for_slice(b.as_bytes()) {
            r.expect("SD with named graphs must be valid N-Triples");
            n += 1;
        }
        assert!(n >= 12, "SD+named-graphs should have many triples, got {n}");
    }

    #[test]
    fn sd_without_named_graphs_emits_no_named_graph_triples() {
        // A dataset with no named graphs (the historical default-only case) must emit NO
        // sd:namedGraph / sd:NamedGraph triples — a pure no-op relative to the prior shape.
        let d = service_description(
            "http://host/sparql",
            "http://host/sparql",
            "http://host/ds",
            &read_only_caps(),
            &[],
            Some("application/n-triples"),
        )
        .unwrap();
        assert!(
            !d.body.contains("#namedGraph") && !d.body.contains("#NamedGraph"),
            "no named graphs ⇒ no sd:namedGraph/NamedGraph triples: {}",
            d.body
        );
    }
}
