#!/usr/bin/env python3
# [OPUS-5] sq-2489d.6 (epic sq-2489d). 🤖 SPARQ agent — GenAI-KB **Phase 7**: the
# per-capability A/B verdict for the provenance-driven KB vs the INERT-PKG baseline.
# Protocol + frozen bar + kill criteria: PREREG-PROVENANCE.md (read it first);
# shared A/B contract: research/dogfooding-sparq-knowledge-graph.md §5.1–§5.6.
#
# WHAT THIS DECIDES — "keep only what measurably pays". Each provenance capability
# (citations / hedging / provenance-weighting) is compared INDEPENDENTLY against the
# same inert-PKG baseline arm P0, and gets its own §5.6 verdict object. A capability
# that does not clear its bar is reported as not clearing it.
#
# THE DIRECTION IS SWAPPED vs the original PKG A/B (PREREG-PROVENANCE.md "direction
# swap"): the treatments here ADD quality and COST tokens, so quality is the
# superiority axis and cost is the non-inferiority axis. The same statistics and the
# same frozen constants are reused — they are IMPORTED from stats.py, never restated,
# so there is exactly one threshold family.
#
# NOTHING here self-reports: tokens come from tokens_real.py (real transcript
# `message.usage`, no char proxy), citation resolution is checked against a
# mechanically-dumped IRI index, and every grade is a deterministic resolver over
# gold/catch keys authored from the SOURCE documents — never from the PKG under test.
#
# Every number produced is runtime-only / NON-CANONICAL. The committed artifacts are
# this code, the pre-registration, and the synthetic self-test fixture.

from __future__ import annotations

import argparse
import json
import statistics as st
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

# The frozen bar + the statistics — single-sourced from the original harness so this
# analyzer cannot drift into a second threshold family (§1.5 "no second threshold set").
from stats import (  # noqa: E402
    BOOTSTRAP_ITERS,
    BOOTSTRAP_SEED,
    MAX_P,
    MIN_N,
    MIN_RELATIVE_REDUCTION,
    bootstrap_median_ci,
    wilcoxon_signed_rank,
)

# Price weighting + the gold-key grader + the loaders — reused from the 3-arm analyzer.
from analyze3 import NEG_RE, PRICE, grade, load_answers, load_tokens  # noqa: E402

BASELINE_ARM = "P0"

# The cost-overhead ceiling for the non-inferiority axis MIRRORS the frozen
# token-reduction constant rather than introducing a new number (PREREG "Thresholds").
COST_OVERHEAD_CEILING = MIN_RELATIVE_REDUCTION

CAPABILITIES = {
    "citations": {
        "arm": "P1",
        "ships_in": "sparq-nlq::cite (Phase 1)",
        "outcome_axis": "stale-fact catch rate on seeded traps (gold-key coverage elsewhere)",
        "trap_class": "stale-fact-trap",
    },
    "hedging": {
        "arm": "P2",
        "ships_in": "sparq-nlq::qualify (Phase 2)",
        "outcome_axis": "abstention precision/recall on out-of-KG traps, over-abstention penalised",
        "trap_class": "abstain-trap",
    },
    "provenance_weighting": {
        "arm": "P3",
        "ships_in": "sparq-vectors provenance-weighted retrieval (Phase 4)",
        "outcome_axis": None,  # pre-registered as blocked — no agent-facing substrate
        "trap_class": None,
    },
}


# --------------------------------------------------------------------------------
# inputs
# --------------------------------------------------------------------------------
def load_runmeta(path: str | None) -> dict:
    """The run record. Absent (or missing a field) is NOT an error — it is a `false`
    on the corresponding honesty condition, named in the verdict."""
    if not path:
        return {}
    return json.loads(Path(path).read_text(encoding="utf-8"))


def load_known_iris(path: str | None) -> set[str] | None:
    """The mechanically-dumped set of IRIs present in the graph the run queried, one
    per line. `None` means citation resolution was NOT verifiable — the citations
    capability is then refused rather than graded on the model's own say-so."""
    if not path:
        return None
    return {
        ln.strip()
        for ln in Path(path).read_text(encoding="utf-8").splitlines()
        if ln.strip() and not ln.startswith("#")
    }


def load_outcome_classes(path: str | None, tasks: dict) -> dict[str, dict]:
    """Per-task outcome class + catch keys. When no file is supplied the abstain-trap
    class is DERIVED from the frozen task set's `negative` stratum (deliberately
    out-of-KG questions are exactly the honest-abstention positives); everything else
    is `ordinary`. Stale-fact traps must be supplied — they are generated by the
    seeding step (PREREG "Seeded stale-fact-trap substrate") and cannot be inferred."""
    out = {
        tid: {
            "outcome_class": "abstain-trap" if t["stratum"] == "negative" else "ordinary",
            "catch_keys": [],
        }
        for tid, t in tasks.items()
    }
    if path:
        for rec in json.loads(Path(path).read_text(encoding="utf-8")):
            if rec["id"] in out:
                out[rec["id"]] = {
                    "outcome_class": rec["outcome_class"],
                    "catch_keys": rec.get("catch_keys", []),
                }
    return out


# --------------------------------------------------------------------------------
# grading (mechanical, arm-blinded — identical code path for baseline and treatment)
# --------------------------------------------------------------------------------
def citation_iris(rec: dict) -> list[str]:
    """The citation IRIs an answer record carries. Accepts a list of IRI strings or a
    list of `{source, anchor}` objects (the CitedAnswer shape)."""
    out: list[str] = []
    for c in rec.get("citations") or []:
        if isinstance(c, str):
            out.append(c)
        else:
            out.extend(str(v) for k, v in c.items() if k in ("source", "anchor") and v)
    return out


def abstained(rec: dict) -> bool:
    """Did the arm abstain? Prefer the structured flag the qualification emits; fall
    back to the same honest-abstention regex the 3-arm analyzer already uses."""
    flag = rec.get("abstained")
    if isinstance(flag, bool):
        return flag
    return bool(NEG_RE.search(rec.get("answer") or ""))


def outcome_score(capability: str, task: dict, cls: dict, rec: dict | None) -> float:
    """The pre-registered per-task outcome score in [0,1]. A missing cell scores 0 —
    an arm that failed to answer did not silently drop out of the pairing."""
    if rec is None:
        return 0.0
    answer = rec.get("answer") or ""
    klass = cls["outcome_class"]
    if capability == "citations":
        if klass == "stale-fact-trap":
            low = answer.lower()
            return 1.0 if any(k.lower() in low for k in cls["catch_keys"]) else 0.0
        return grade(task, answer)
    if capability == "hedging":
        if klass == "abstain-trap":
            return 1.0 if abstained(rec) else 0.0
        # over-abstention on an answerable task is a zero, not a free pass
        return 0.0 if abstained(rec) else grade(task, answer)
    raise ValueError(f"no outcome axis for capability {capability!r}")


def abstention_stats(traps: list[str], ordinary: list[str], recs: dict[str, dict | None]) -> dict:
    """Abstention precision/recall for ONE arm, over the whole paired task set.

    The positives are the `abstain-trap` tasks (abstaining there is correct); the
    answerable tasks are the negatives, so an abstention on one is a FALSE POSITIVE.
    A missing cell did not abstain — it is a false negative on a trap, never a false
    positive on an answerable task. Precision is `None` (undefined, never 1.0) when
    the arm made no abstention decision at all."""
    tp = sum(1 for t in traps if recs.get(t) is not None and abstained(recs[t]))
    fn = len(traps) - tp
    fp = sum(1 for t in ordinary if recs.get(t) is not None and abstained(recs[t]))
    return {
        "true_positive": tp,
        "false_positive": fp,
        "false_negative": fn,
        "precision": (round(tp / (tp + fp), 4) if (tp + fp) else None),
        "recall": (round(tp / (tp + fn), 4) if (tp + fn) else None),
        # over-abstention on answerable tasks, always defined — this is what the mean
        # ordinary score cannot see when the baseline was already scoring badly there
        "false_positive_rate": (round(fp / len(ordinary), 4) if ordinary else None),
    }


def _ratio(x: float | None) -> str:
    """An undefined rate prints as `—`, never as a number the run did not earn."""
    return "—" if x is None else f"{x:.2f}"


def citation_guards(recs: list[dict], known: set[str] | None) -> dict:
    """Citation-resolution rate + fabricated-citation count, checked against the
    graph's IRI index. `verified=False` when no index was supplied."""
    if known is None:
        return {"verified": False, "resolution_rate": None, "fabricated": None, "emitted": None}
    emitted = fabricated = 0
    for r in recs:
        for iri in citation_iris(r):
            emitted += 1
            if iri not in known:
                fabricated += 1
    return {
        "verified": True,
        "emitted": emitted,
        "fabricated": fabricated,
        "resolution_rate": (round((emitted - fabricated) / emitted, 4) if emitted else None),
    }


def dollars(rec: dict, family: str) -> float:
    price_in, price_out = PRICE.get(family, PRICE["opus"])
    return (
        rec["eff_input_tokens"] / 1e6 * price_in
        + rec.get("output_tokens", 0) / 1e6 * price_out
    )


# --------------------------------------------------------------------------------
# the per-capability verdict
# --------------------------------------------------------------------------------
def blocked(capability: str, why: str) -> dict:
    """A capability we cannot honestly measure is EMITTED as blocked, never omitted —
    an absent capability reads as 'nothing to see', a blocked one names the gap."""
    spec = CAPABILITIES[capability]
    return {
        "capability": capability,
        "ships_in": spec["ships_in"],
        "arm": spec["arm"],
        "status": "blocked",
        "blocked_reason": why,
        "token_win": False,
        "token_delta_median_pct": None,
        "token_delta_ci": None,
        "quality_delta": {"exec_acc": {}, "provenance_completeness": {}, "hallucination_rate": {}},
        "break_even_N": None,
        "break_even_infinite": False,
        "honest": False,
        "recommend_adopt": False,
    }


def verdict_for(
    capability: str,
    tasks: dict,
    classes: dict,
    tok: dict,
    answers: dict,
    known: set[str] | None,
    run: dict,
) -> dict:
    spec = CAPABILITIES[capability]
    arm = spec["arm"]

    if spec["outcome_axis"] is None:
        return blocked(
            capability,
            "pre-registered as blocked: no agent-facing task substrate exists. Phase 4's "
            "offline Hits@k / MRR on a held-out link-prediction split is not an agent-outcome "
            "measure and must not be substituted for one (needs its own bead).",
        )

    paired = sorted(t for t in tasks if (t, BASELINE_ARM) in tok and (t, arm) in tok)
    if not paired:
        return blocked(capability, f"arm {arm} was not run (no paired {BASELINE_ARM}/{arm} cells)")

    fam = (run.get("models") or {})
    base_cost = [dollars(tok[(t, BASELINE_ARM)], fam.get(BASELINE_ARM, "opus")) for t in paired]
    treat_cost = [dollars(tok[(t, arm)], fam.get(arm, "opus")) for t in paired]
    cost_delta = [b - x for b, x in zip(base_cost, treat_cost)]  # +ve = treatment cheaper

    # The superiority test runs on the TRAP subset — the tasks where the capability can
    # act at all. Diluting it with tasks the capability cannot affect drives the paired
    # median to exactly 0 and would make superiority unreachable by construction; the
    # non-trap tasks are not discarded, they carry the non-regression guard below.
    traps = [t for t in paired if classes[t]["outcome_class"] == spec["trap_class"]]
    trap_set = set(traps)
    ordinary = [t for t in paired if t not in trap_set]

    def scores(ids: list[str], which: str) -> list[float]:
        return [outcome_score(capability, tasks[t], classes[t], answers.get((t, which))) for t in ids]

    base_q, treat_q = scores(traps, BASELINE_ARM), scores(traps, arm)
    q_delta = [x - b for b, x in zip(base_q, treat_q)]

    n = len(paired)
    med_base_cost = st.median(base_cost)
    med_treat_cost = st.median(treat_cost)
    overhead = (med_treat_cost - med_base_cost) / med_base_cost if med_base_cost else float("inf")
    c_lo, c_hi = bootstrap_median_ci(cost_delta, BOOTSTRAP_ITERS, BOOTSTRAP_SEED)
    cost_non_inferior = bool(
        overhead <= COST_OVERHEAD_CEILING and c_lo > -COST_OVERHEAD_CEILING * med_base_cost
    )

    med_q_delta = st.median(q_delta) if q_delta else 0.0
    _w, q_p = wilcoxon_signed_rank(q_delta) if q_delta else (0.0, None)
    q_lo, q_hi = bootstrap_median_ci(q_delta, BOOTSTRAP_ITERS, BOOTSTRAP_SEED) if q_delta else (0.0, 0.0)
    quality_superior = bool(med_q_delta > 0 and q_p is not None and q_p < MAX_P and q_lo > 0)

    guards = citation_guards([answers[(t, arm)] for t in paired if (t, arm) in answers], known)
    fabricated = guards["fabricated"]

    # Non-regression on the tasks the capability is NOT supposed to change — a
    # trap-catch gain must not be bought by degrading the everyday answers (§5.4 KILL 3).
    # Scored on the same capability-aware axis, so `hedging` cannot buy abstention recall
    # by abstaining on answerable questions.
    acc_base = st.mean(scores(ordinary, BASELINE_ARM)) if ordinary else None
    acc_treat = st.mean(scores(ordinary, arm)) if ordinary else None
    acc_non_regression = acc_base is None or acc_treat >= acc_base

    # ABSTENTION PRECISION (hedging only, §5.4 KILL 3 "regresses abstention precision").
    # The mean ordinary score above is NOT a precision guard: where the baseline was
    # already scoring 0 the treatment can abstain on an ANSWERABLE task, hold the mean at
    # or above baseline, and still have turned a wrong answer into a false-positive
    # abstention. So the abstention decisions are counted directly and reported for BOTH
    # arms — the axis this capability pre-registered ("abstention precision/recall on
    # out-of-KG traps, over-abstention penalised") is emitted, not merely declared.
    abstention = None
    precision_non_regression = True
    if capability == "hedging":
        base_ab = abstention_stats(traps, ordinary, {t: answers.get((t, BASELINE_ARM)) for t in paired})
        treat_ab = abstention_stats(traps, ordinary, {t: answers.get((t, arm)) for t in paired})
        # Over-abstention is a regression if the treatment abstains on a LARGER share of
        # answerable tasks than the baseline did (always defined, and the only comparison
        # available when the baseline never abstained at all), or — when both arms did
        # abstain — if the treatment's precision is strictly lower.
        fp_worse = (treat_ab["false_positive_rate"] or 0.0) > (base_ab["false_positive_rate"] or 0.0)
        prec_worse = (
            base_ab["precision"] is not None
            and treat_ab["precision"] is not None
            and treat_ab["precision"] < base_ab["precision"]
        )
        precision_non_regression = not (fp_worse or prec_worse)
        abstention = {
            "baseline": base_ab,
            "treatment": treat_ab,
            "precision_non_regression": precision_non_regression,
            "answerable_tasks": len(ordinary),
        }

    extra_wins = sum(treat_q) - sum(base_q)
    extra_spend = sum(treat_cost) - sum(base_cost)
    cost_per_extra_win = round(extra_spend / extra_wins, 6) if extra_wins > 0 else None

    substrate_present = bool(traps)

    honesty = {
        "real_transcript_tokens": run.get("token_source") == "real-transcript",
        "counterbalanced": run.get("counterbalanced") is True,
        "n_paired_at_least_min_n": n >= MIN_N,
        # the BINDING N: the superiority test only sees the trap subset
        "n_traps_at_least_min_n": len(traps) >= MIN_N,
        # a treatment arm that emits no capability evidence is a placebo, not a treatment
        "arm_wiring_verified": _wiring_verified(capability, [answers.get((t, arm)) for t in paired]),
        "canonical_host_declared": bool(run.get("canonical_host")),
        "fable_rerun": run.get("fable_rerun") is True,
        "grader_arm_blinded": True,  # one mechanical resolver, identical for both arms
        "outcome_substrate_present": substrate_present,
    }
    if capability == "citations":
        honesty["citation_resolution_verified"] = bool(guards["verified"])
    honest = all(honesty.values())

    kills = []
    if not cost_non_inferior:
        kills.append(
            {
                "kill": "KILL_1_cost",
                "fired": True,
                "why": f"median cost overhead {overhead:.1%} > ceiling "
                f"{COST_OVERHEAD_CEILING:.0%}, or the paired-delta CI lower bound "
                f"{c_lo:.6f} falls below the non-inferiority margin",
            }
        )
    if extra_wins <= 0:
        kills.append(
            {
                "kill": "KILL_2_break_even",
                "fired": True,
                "why": "the treatment wins no more task outcomes than the baseline — the "
                "extra spend buys nothing, so there is no break-even",
            }
        )
    if (
        not quality_superior
        or not acc_non_regression
        or not precision_non_regression
        or (fabricated or 0) > 0
    ):
        why = []
        if not quality_superior:
            why.append(
                f"outcome superiority not established (median delta {med_q_delta:+.3f}, "
                f"p={q_p}, CI lower bound {q_lo:+.3f})"
            )
        if not acc_non_regression:
            why.append(f"ordinary-task accuracy regressed ({acc_base:.2f} → {acc_treat:.2f})")
        if not precision_non_regression:
            b, x = abstention["baseline"], abstention["treatment"]
            why.append(
                f"abstention precision regressed (baseline {_ratio(b['precision'])} → "
                f"treatment {_ratio(x['precision'])}): {x['false_positive']} false-positive "
                f"abstention(s) on {len(ordinary)} answerable task(s) vs "
                f"{b['false_positive']} for the baseline"
            )
        if (fabricated or 0) > 0:
            why.append(f"{fabricated} fabricated citation(s) — hard kill")
        kills.append({"kill": "KILL_3_quality", "fired": True, "why": "; ".join(why)})

    recommend = bool(
        honest and cost_non_inferior and quality_superior and precision_non_regression and not kills
    )

    return {
        "capability": capability,
        "ships_in": spec["ships_in"],
        "arm": arm,
        "status": "measured",
        # --- the shared §5.6 object ---
        "token_win": cost_non_inferior,  # Phase 7: "cleared the COST criterion" (see _detail)
        "token_delta_median_pct": round(
            ((med_base_cost - med_treat_cost) / med_base_cost * 100) if med_base_cost else 0.0, 1
        ),
        "token_delta_ci": [round(c_lo, 6), round(c_hi, 6)],
        "quality_delta": {
            "exec_acc": {
                "non_trap_tasks": len(ordinary),
                "baseline": (None if acc_base is None else round(acc_base, 4)),
                "treatment": (None if acc_treat is None else round(acc_treat, 4)),
                "non_regression": bool(acc_non_regression),
            },
            "provenance_completeness": guards,
            "hallucination_rate": {
                "fabricated_citations": fabricated,
                "note": "fabricated citations are the mechanically-checkable hallucination "
                "proxy here (an IRI absent from the graph the answer was drawn from); "
                "free-prose hallucination is not measured by this harness",
            },
        },
        "break_even_N": None,
        "break_even_infinite": False,
        "honest": honest,
        "recommend_adopt": recommend,
        # --- supporting detail (runtime-only, NON-CANONICAL) ---
        "_detail": {
            "criterion": "quality SUPERIORITY + cost NON-INFERIORITY (Phase-7 direction "
            "swap — `token_win` carries 'cleared the cost criterion', not 'spent fewer "
            "tokens'); see PREREG-PROVENANCE.md",
            "outcome_axis": spec["outcome_axis"],
            "n_paired": n,
            "n_traps": len(traps),
            "n_non_trap": len(ordinary),
            "superiority_tested_on": f"{spec['trap_class']} subset (n={len(traps)})",
            "median_cost_baseline_usd": round(med_base_cost, 6),
            "median_cost_treatment_usd": round(med_treat_cost, 6),
            "cost_overhead_pct": round(overhead * 100, 1),
            "cost_overhead_ceiling_pct": round(COST_OVERHEAD_CEILING * 100, 1),
            "cost_non_inferior": cost_non_inferior,
            "outcome_median_delta": round(med_q_delta, 4),
            "outcome_wilcoxon_p": q_p,
            "outcome_delta_ci": [round(q_lo, 4), round(q_hi, 4)],
            "quality_superior": quality_superior,
            # the declared hedging axis, measured — `None` for capabilities without one
            "abstention": abstention,
            "cost_per_extra_caught_defect_usd": cost_per_extra_win,
            "break_even_note": "break_even_N is undefined in the token sense for a "
            "quality-ADDING capability; its analogue is cost_per_extra_caught_defect_usd",
            "honesty": honesty,
            "kill_criteria": kills,
            "token_delta_ci_units": "USD per task (paired baseline − treatment)",
            "prices_per_mtok": PRICE,
            "frozen_bar": {
                "min_relative_reduction": MIN_RELATIVE_REDUCTION,
                "max_p": MAX_P,
                "min_n": MIN_N,
                "source": "stats.py (imported, not restated)",
            },
        },
    }


def _wiring_verified(capability: str, recs: list[dict | None]) -> bool:
    """Did the treatment arm actually exercise the capability? A treatment arm whose
    answers are indistinguishable from the baseline's is a placebo — blocker 3 in
    PREREG-PROVENANCE.md (the `pkg-query` envelope does not yet carry either field)."""
    live = [r for r in recs if r]
    if not live:
        return False
    if capability == "citations":
        return any(citation_iris(r) for r in live)
    if capability == "hedging":
        return any(r.get("hedge") or isinstance(r.get("abstained"), bool) for r in live)
    return False


# --------------------------------------------------------------------------------
def build_verdict(
    tasks_path: str,
    token_paths: list[str],
    answer_paths: list[str],
    runmeta_path: str | None,
    known_iris_path: str | None,
    capability_tasks_path: str | None,
) -> dict:
    tasks = {t["id"]: t for t in json.loads(Path(tasks_path).read_text(encoding="utf-8"))}
    tok = load_tokens(token_paths)
    raw_answers = _load_answer_records(answer_paths)
    run = load_runmeta(runmeta_path)
    known = load_known_iris(known_iris_path)
    classes = load_outcome_classes(capability_tasks_path, tasks)

    caps = {
        name: verdict_for(name, tasks, classes, tok, raw_answers, known, run)
        for name in CAPABILITIES
    }
    adopt = sorted(k for k, v in caps.items() if v["recommend_adopt"])
    blocked_caps = sorted(k for k, v in caps.items() if v["status"] == "blocked")
    # "drop" means MEASURED HONESTLY AND DID NOT PAY. A capability whose run failed the
    # honesty gate is INCONCLUSIVE, not dropped — filing it under `drop` would report a
    # verdict the measurement did not earn (the §5.1 "no evidence ≠ no effect" rule).
    inconclusive = sorted(
        k for k, v in caps.items() if v["status"] == "measured" and not v["honest"]
    )
    drop = sorted(
        k for k, v in caps.items()
        if v["status"] == "measured" and v["honest"] and not v["recommend_adopt"]
    )
    # A blocked capability is honestly reported AS blocked (and named in `blocked`), so it
    # does not make the roll-up dishonest — it would otherwise be impossible for the
    # roll-up ever to be honest while one capability lacks a substrate. What would be
    # dishonest is a MEASURED capability whose measurement did not clear the honesty gate.
    all_honest = all(v["honest"] for v in caps.values() if v["status"] == "measured")

    return {
        "bead": "sq-2489d.6",
        "phase": "GenAI-KB Phase 7 — provenance-driven KB vs inert-PKG baseline",
        "prereg": "bench/pkg-dogfood/PREREG-PROVENANCE.md",
        "baseline_arm": BASELINE_ARM,
        "capabilities": caps,
        "adopt": adopt,
        "drop": drop,
        "inconclusive": inconclusive,
        "blocked": blocked_caps,
        "honest": all_honest,
        "honesty_note": "every MEASURED capability cleared the honesty gate; blocked "
        "capabilities are listed in `blocked` with their reason, not silently dropped",
        "recommend_adopt": bool(adopt) and all_honest,
        "_run": run,
        "_non_canonical": True,
    }


def _load_answer_records(paths: list[str]) -> dict[tuple[str, str], dict]:
    """Like `analyze3.load_answers`, but keeps the WHOLE record (citations / hedge /
    abstained), which the capability grading needs. Falls back to the plain
    `{"task|arm": "answer"}` map shape that analyzer accepts."""
    out: dict[tuple[str, str], dict] = {}
    for p in paths:
        data = json.loads(Path(p).read_text(encoding="utf-8"))
        if isinstance(data, dict) and "result" in data:
            data = data.get("result", {}).get("results") or []
        if isinstance(data, dict):
            for key, ans in load_answers([p]).items():
                out[key] = {"answer": ans}
            continue
        for rec in data:
            out[(rec["task"], rec["arm"])] = rec
    return out


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--tasks", default=str(HERE / "tasks" / "abm_tasks.json"))
    ap.add_argument("--tokens", nargs="+", required=True, help="tokens_real.py output JSON(s)")
    ap.add_argument("--answers", nargs="+", required=True, help="per-(task,arm) answer records")
    ap.add_argument("--runmeta", default=None, help="run record (host / models / token source)")
    ap.add_argument("--known-iris", default=None, help="IRIs present in the queried graph")
    ap.add_argument("--capability-tasks", default=None, help="per-task outcome classes + catch keys")
    ap.add_argument("--out", default=None)
    args = ap.parse_args(argv[1:])

    verdict = build_verdict(
        args.tasks, args.tokens, args.answers, args.runmeta, args.known_iris, args.capability_tasks
    )

    print("=== GenAI-KB PHASE 7 — per-capability verdict (NON-CANONICAL, runtime-only) ===")
    print(f"baseline: arm {BASELINE_ARM} (inert PKG)   prereg: {verdict['prereg']}\n")
    print(f"{'capability':22} {'arm':4} {'status':9} {'cost Δ%':>9} {'outcome Δ':>10} "
          f"{'honest':>7} {'adopt':>6}")
    for name, v in verdict["capabilities"].items():
        d = v.get("_detail", {})
        cost = "—" if v["token_delta_median_pct"] is None else f"{v['token_delta_median_pct']:+.1f}"
        outcome = "—" if "outcome_median_delta" not in d else f"{d['outcome_median_delta']:+.3f}"
        print(f"{name:22} {v['arm']:4} {v['status']:9} {cost:>9} {outcome:>10} "
              f"{str(v['honest']):>7} {str(v['recommend_adopt']):>6}")
        if v["status"] == "blocked":
            print(f"    blocked: {v['blocked_reason']}")
        ab = d.get("abstention")
        if ab:
            print(
                f"    abstention precision {_ratio(ab['baseline']['precision'])} → "
                f"{_ratio(ab['treatment']['precision'])}   recall "
                f"{_ratio(ab['baseline']['recall'])} → {_ratio(ab['treatment']['recall'])}   "
                f"false-positive abstentions {ab['baseline']['false_positive']} → "
                f"{ab['treatment']['false_positive']} of {ab['answerable_tasks']} answerable"
            )
        for failed in [k for k, ok in d.get("honesty", {}).items() if not ok]:
            print(f"    not honest yet: {failed}")
        for k in d.get("kill_criteria", []):
            print(f"    {k['kill']}: {k['why']}")

    print(
        f"\nadopt={verdict['adopt']}  drop={verdict['drop']}  "
        f"inconclusive={verdict['inconclusive']}  blocked={verdict['blocked']}"
    )
    print(f"honest={verdict['honest']}  recommend_adopt={verdict['recommend_adopt']}")

    if args.out:
        Path(args.out).write_text(json.dumps(verdict, indent=2) + "\n", encoding="utf-8")
        print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
