//! Generated-schedule convergence properties (`sq-tag1q.7.4`).
//!
//! Random origin scripts run offline on several replicas; random schedules
//! then permute, duplicate, batch, snapshot-join, compact, and replay the
//! resulting deltas, with late origin activity racing the deliveries. After a
//! completion pass (every envelope reaches every replica, per-replica order
//! shuffled), the `CRDT-SEC-2` equalities must hold and every replica must
//! equal the order-independent fold of all deltas — the semilattice
//! least-upper-bound oracle. These are *sampled* property tests: evidence and
//! regression protection, not a proof of convergence.

use proptest::prelude::*;
// [OPUS-5] `Dot` here is the MODEL dot (`context::Dot`); the crate root's `Dot` is the
// wire type from the codec layer (`id::Dot`, bead sq-tag1q.7.2). The two are distinct
// by design, so the model's is imported by its module path rather than re-exported.
use sparq_crdt::context::Dot;
use sparq_crdt::{
    assert_converged, deliver_all, run_schedule, CausalContext, Envelope, GraphKey, Op, Quad,
    Replica, State, Step,
};

const REPLICAS: usize = 3;

fn arb_quad() -> impl Strategy<Value = Quad> {
    (
        0u8..2,
        0u8..2,
        0u8..2,
        prop_oneof![Just(GraphKey::Default), (0u8..2).prop_map(GraphKey::Named)],
    )
        .prop_map(|(s, p, o, g)| Quad::new(s, p, o, g))
}

fn arb_op() -> impl Strategy<Value = Op> {
    prop_oneof![
        prop::collection::vec(arb_quad(), 1..3).prop_map(Op::InsertData),
        prop::collection::vec(arb_quad(), 1..3).prop_map(Op::DeleteData),
        (
            prop::collection::vec(arb_quad(), 0..2),
            prop::collection::vec(arb_quad(), 0..2)
        )
            .prop_map(|(delete, insert)| Op::DeleteInsertWhere { delete, insert }),
        (0u8..2).prop_map(Op::DeleteWherePredicate),
    ]
}

fn arb_scripts(max_ops: usize) -> impl Strategy<Value = Vec<Vec<Op>>> {
    prop::collection::vec(prop::collection::vec(arb_op(), 0..=max_ops), REPLICAS)
}

/// Raw schedule material: `(kind, a, b, batch)` interpreted modulo the live
/// replica/envelope counts, so generation is independent of how many
/// envelopes the generated scripts produced.
type RawStep = (u8, u8, u8, Vec<u8>);

fn arb_raw_steps(max: usize) -> impl Strategy<Value = Vec<RawStep>> {
    prop::collection::vec(
        (
            any::<u8>(),
            any::<u8>(),
            any::<u8>(),
            prop::collection::vec(any::<u8>(), 0..4),
        ),
        0..=max,
    )
}

fn interpret(raw: &[RawStep], n_envelopes: usize) -> Vec<Step> {
    let mut steps = Vec::new();
    for (kind, a, b, batch) in raw {
        let to = usize::from(*a) % REPLICAS;
        match kind % 4 {
            0 | 1 if n_envelopes > 0 => {
                let envelope = usize::from(*b) % n_envelopes;
                if kind % 4 == 0 {
                    steps.push(Step::Deliver { to, envelope });
                } else {
                    steps.push(Step::DeliverBatch {
                        to,
                        envelopes: batch
                            .iter()
                            .map(|&e| usize::from(e) % n_envelopes)
                            .collect(),
                    });
                }
            }
            2 => steps.push(Step::SnapshotSync {
                from: usize::from(*b) % REPLICAS,
                to,
            }),
            3 => steps.push(Step::Compact { at: to }),
            _ => {} // envelope-referencing step with no envelopes published yet
        }
    }
    steps
}

/// Deterministic shuffle of `0..len` driven by generated bytes (swaps preserve
/// the permutation property `deliver_all` requires).
fn permutation(len: usize, seed: &[u8]) -> Vec<usize> {
    let mut order: Vec<usize> = (0..len).collect();
    if len > 1 {
        for (i, &byte) in seed.iter().enumerate() {
            order.swap(i % len, usize::from(byte) % len);
        }
    }
    order
}

proptest! {
    /// End-to-end convergence: offline scripts, arbitrary schedule prefix,
    /// late origin activity racing deliveries, a second schedule, then a
    /// completion pass — all replicas must satisfy `CRDT-SEC-2` and equal the
    /// order-independent fold of every published delta. Afterwards, replaying
    /// any single envelope must change nothing (duplicate tolerance).
    #[test]
    fn generated_schedules_converge_to_the_join_of_all_deltas(
        scripts in arb_scripts(3),
        late_ops in arb_scripts(1),
        raw_early in arb_raw_steps(10),
        raw_late in arb_raw_steps(6),
        shuffle in prop::collection::vec(any::<u8>(), 0..16),
    ) {
        let mut replicas: Vec<Replica> = (0..REPLICAS).map(|i| Replica::new(i as u8)).collect();
        let mut envelopes: Vec<Envelope> = Vec::new();
        for (replica, script) in replicas.iter_mut().zip(&scripts) {
            envelopes.extend(replica.execute_request(script));
        }
        let early = interpret(&raw_early, envelopes.len());
        prop_assert_eq!(run_schedule(&mut replicas, &envelopes, &early), Ok(()));

        // Late origin activity: pattern updates here race the deliveries above.
        for (replica, script) in replicas.iter_mut().zip(&late_ops) {
            envelopes.extend(replica.execute_request(script));
        }
        let late = interpret(&raw_late, envelopes.len());
        prop_assert_eq!(run_schedule(&mut replicas, &envelopes, &late), Ok(()));

        let order = permutation(envelopes.len(), &shuffle);
        prop_assert_eq!(deliver_all(&mut replicas, &envelopes, &order), Ok(()));
        prop_assert_eq!(assert_converged(&replicas), Ok(()));

        // Order-independence oracle: every replica equals the fold of all deltas.
        let reference = envelopes
            .iter()
            .fold(State::bottom(), |acc, e| acc.join(&e.to_delta()));
        prop_assert_eq!(replicas[0].state(), &reference);

        // Replay after quiescence: duplicates are harmless.
        for (i, envelope) in envelopes.iter().enumerate() {
            let replica = &mut replicas[i % REPLICAS];
            let before = replica.state().clone();
            prop_assert_eq!(replica.apply(&envelope.to_delta()), Ok(()));
            prop_assert_eq!(replica.state(), &before);
        }
    }

    /// `CRDT-UPD-BATCH-1`: joining a request's per-operation delta fragments
    /// into one batch yields the same state as ordered sequential evaluation.
    #[test]
    fn batched_request_delta_equals_sequential_evaluation(
        setup in prop::collection::vec(arb_op(), 0..3),
        request in prop::collection::vec(arb_op(), 0..4),
    ) {
        let mut replica = Replica::new(7);
        replica.execute_request(&setup);
        let before = replica.state().clone();
        let envelopes = replica.execute_request(&request);
        let batched = Replica::batched_delta(&envelopes);
        prop_assert_eq!(&before.join(&batched), replica.state());
    }

    /// Join laws as sampled properties over origin-generated deltas and their
    /// partial joins: idempotent, commutative, associative (`CRDT-JOIN-1`).
    #[test]
    fn join_laws_hold_on_generated_deltas(scripts in arb_scripts(2)) {
        let mut replicas: Vec<Replica> = (0..REPLICAS).map(|i| Replica::new(i as u8)).collect();
        let mut deltas: Vec<State> = Vec::new();
        for (replica, script) in replicas.iter_mut().zip(&scripts) {
            deltas.extend(replica.execute_request(script).iter().map(Envelope::to_delta));
        }
        deltas.truncate(5);
        for a in &deltas {
            prop_assert_eq!(&a.join(a), a);
            for b in &deltas {
                prop_assert_eq!(a.join(b), b.join(a));
                for c in &deltas {
                    prop_assert_eq!(a.join(b).join(c), a.join(&b.join(c)));
                }
            }
        }
    }

    /// `CRDT-CTX-1`: a causal context's denotation survives construction from
    /// arbitrary dot sets, compaction round-trips, and union; union is the
    /// denotation union and is idempotent/commutative.
    #[test]
    fn causal_context_denotation_survives_compaction_and_union(
        dots_a in prop::collection::btree_set(
            (0u8..3, 1u64..6).prop_map(|(r, c)| Dot::new(r, c)), 0..10),
        dots_b in prop::collection::btree_set(
            (0u8..3, 1u64..6).prop_map(|(r, c)| Dot::new(r, c)), 0..10),
    ) {
        let a = CausalContext::from_dots(dots_a.iter().copied());
        prop_assert_eq!(a.dots(), dots_a.clone());
        let (clock, cloud) = a.decompacted();
        let back = CausalContext::from_parts(clock, cloud);
        prop_assert!(back.denotation_eq(&a));
        prop_assert_eq!(&back, &a);

        let b = CausalContext::from_dots(dots_b.iter().copied());
        prop_assert_eq!(a.union(&b), b.union(&a));
        prop_assert_eq!(a.union(&a), a.clone());
        let mut expected = dots_a.clone();
        expected.extend(dots_b.iter().copied());
        prop_assert_eq!(a.union(&b).dots(), expected);
    }
}
