#!/usr/bin/env python3
# CI lint (bead sq-53cq): anti-drift guard that every served-class
# source asset under bench/dashboard/ is actually WIRED into the Pages publisher.
#
# WHY THIS GATE EXISTS — the two-hop dashboard publish has no propagation check:
#   bench/dashboard/* is the in-repo SOURCE OF TRUTH for the public benchmark
#   dashboard. It reaches the live site over TWO hops, neither of which is checked
#   against the in-repo source at PR time:
#     1. bench.yml's "Seed Pages dashboard onto benchmark-data" step copies a
#        HARD-CODED list of files (`for f in index.html dashboard.js …`) from
#        bench/dashboard/ onto the `benchmark-data` branch under dev/bench/, plus
#        root-redirect.html → the branch ROOT as index.html.
#     2. pages.yml then `git archive origin/benchmark-data dev` folds that dev/
#        subtree into the Pages artifact (out/dev/) that goes live.
#   The footgun: the seed list in step 1 is a hand-maintained literal. Add a NEW
#   asset to bench/dashboard/ (as happened with competitors.json) and forget to add
#   it to that `for f in …` list, and the asset lands in-repo but is NEVER copied to
#   benchmark-data — so it NEVER reaches the served dashboard. There is no error: the
#   seed step just doesn't copy a file it was never told about, pages.yml folds what
#   IS on the branch, and the site silently serves a stale/incomplete dashboard.
#
# WHAT THIS CHECKS (deterministic, in-repo, NO network / NO benchmark-data fetch):
#   Every served-class source asset tracked under bench/dashboard/ MUST be wired into
#   the publisher — i.e. it must appear EITHER in bench.yml's seed `for f in …` list
#   (relative to bench/dashboard/) OR be the dedicated root-redirect.html (which the
#   seed step copies to the branch root). A served-class asset that is in neither is
#   genuine source-of-truth drift: an edit/addition that can never reach the site.
#
#   We do NOT diff bench/dashboard/* against the live copy on the benchmark-data
#   branch. That copy LAGS by design — bench.yml only re-seeds on a push to main (the
#   full bench job), so during a PR (and until the next main bench run) the served
#   copy is legitimately BEHIND the in-repo edit. A strict "in-repo == served" diff
#   would therefore be RED on every honest dashboard PR and on any commit between a
#   dashboard edit and the next main bench run — punishing exactly the normal flow.
#   The durable, gateable invariant is the WIRING (source asset → seed list), not the
#   transient lag; this check guards the wiring so a new asset can't be silently
#   un-published, while leaving the lag (which self-heals on the next main run) alone.
#
# DOCUMENTED EXCLUSIONS (NOT served, so not expected in the seed list):
#   - vendor/README.md   — vendoring-provenance doc for vendor/Chart.min.js; it is
#                          documentation, never fetched by the dashboard, and is
#                          deliberately NOT seeded. Excluded by the SERVED_EXCLUDE set
#                          below (any *.md under bench/dashboard/ is treated the same:
#                          docs, not a served asset).
#   The set of files the dashboard actually serves is the static source assets named
#   in the bead — index.html, dashboard.css, dashboard.js, metric-labels.json,
#   competitors.json, root-redirect.html — plus the vendored runtime dep
#   vendor/Chart.min.js. Each of those must be wired; only *.md (provenance docs) and
#   data.js (GENERATED by github-action-benchmark on the branch, never sourced from
#   bench/dashboard/) are out of scope.
#
# WHY A HAND-ROLLED PARSER (no PyYAML): this runs in the docs-quality `ci-scripts`
# job, which installs no Python deps (mirrors check-install-action-tool.py /
# coverage-gate.py --self-test). We only need to (a) find bench.yml's seed step's
# `for f in … ; do` line and split out its file list, and (b) confirm root-redirect
# is copied. A small regex over the workflow text is sufficient and dependency-free.
#
# EXIT: 0 when every served-class bench/dashboard asset is wired into the publisher
# (or there are none); 1 with a per-offence message otherwise.
#
# Usage:
#   check-dashboard-publish-wiring.py                # check this repo
#   check-dashboard-publish-wiring.py --root <dir>   # check <dir>
#   check-dashboard-publish-wiring.py --self-test    # hermetic logic self-test
#
# stdlib-only.

from __future__ import annotations

import argparse
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent

# The in-repo source-of-truth dir and the publisher workflow that seeds it.
DASHBOARD_DIR = "bench/dashboard"
BENCH_WORKFLOW = ".github/workflows/bench.yml"

# The dedicated root-redirect asset: the seed step copies it to the benchmark-data
# branch ROOT as index.html (NOT into the dev/bench `for f in …` loop), so it is
# wired via its own copy line rather than via the seed list.
ROOT_REDIRECT = "root-redirect.html"

# Served-class EXCLUSIONS: files tracked under bench/dashboard/ that the dashboard
# does NOT serve, so they are intentionally NOT in the seed list. Matched by basename
# OR suffix. `*.md` = vendoring/provenance docs (e.g. vendor/README.md).
SERVED_EXCLUDE_SUFFIXES = (".md",)

# `for f in <files> ; do` — the seed step's file loop. Captures everything between
# `for f in` and the terminating `;`/`do`. We tolerate arbitrary leading indent.
_FOR_LOOP_RE = re.compile(r"^\s*for\s+f\s+in\s+(?P<files>.+?)\s*;\s*do\b", re.MULTILINE)


def is_served_asset(rel_path: str) -> bool:
    """True if `rel_path` (relative to bench/dashboard/) is a SERVED-class source
    asset whose wiring this gate enforces. Excludes provenance docs (*.md) and the
    generated data.js (never sourced from bench/dashboard/ — it is written on the
    benchmark-data branch by github-action-benchmark)."""
    if rel_path.endswith(SERVED_EXCLUDE_SUFFIXES):
        return False
    if rel_path == "data.js":  # generated on-branch, never an in-repo source asset
        return False
    return True


def seed_list_files(workflow_text: str) -> set[str] | None:
    """Extract the set of bench/dashboard-relative file paths from bench.yml's seed
    `for f in … ; do` loop. Returns None if no such loop is found (so the caller can
    report a structural change to the seed step rather than silently passing)."""
    m = _FOR_LOOP_RE.search(workflow_text)
    if m is None:
        return None
    raw = m.group("files")
    # The loop iterates space-separated literal paths (relative to $src =
    # bench/dashboard). Split on whitespace; drop any stray shell tokens defensively.
    return {tok for tok in raw.split() if tok and not tok.startswith("$")}


def seeds_root_redirect(workflow_text: str) -> bool:
    """True if the workflow copies root-redirect.html (the dedicated root-redirect
    asset, seeded to the branch root rather than via the `for f in …` loop)."""
    return ROOT_REDIRECT in workflow_text


def tracked_dashboard_assets(root: Path) -> list[str]:
    """List bench/dashboard-relative paths of every tracked file under the dashboard
    dir (recursive). Filesystem walk — in CI the checkout has the full tree; the
    *.md / data.js filtering happens in is_served_asset(), so a non-tracked stray
    file would only ever ADD a (correctly-flagged) offence, never hide one."""
    base = root / DASHBOARD_DIR
    if not base.is_dir():
        return []
    out: list[str] = []
    for p in sorted(base.rglob("*")):
        if p.is_file():
            out.append(p.relative_to(base).as_posix())
    return out


def find_offences(workflow_text: str, assets: list[str]) -> list[str]:
    """Return a list of bench/dashboard-relative paths that are SERVED-class source
    assets but are NOT wired into the publisher (neither in the seed `for f in …`
    list nor the root-redirect copy). A sentinel offence is returned if the seed loop
    itself can't be located (the step shape changed out from under this gate)."""
    seed = seed_list_files(workflow_text)
    if seed is None:
        return ["<seed-loop-not-found>"]
    has_root_redirect = seeds_root_redirect(workflow_text)
    offences: list[str] = []
    for rel in assets:
        if not is_served_asset(rel):
            continue
        if rel == ROOT_REDIRECT:
            # Wired iff the dedicated root-redirect copy line is present.
            if not has_root_redirect:
                offences.append(rel)
            continue
        if rel not in seed:
            offences.append(rel)
    return offences


# --------------------------------------------------------------------------- tests
# A faithful miniature of bench.yml's seed step: the `for f in …` loop + the separate
# root-redirect copy. The self-test drives find_offences() against synthetic asset
# lists so the gate's own logic is pinned without touching the live workflow.
_SEED_OK = """\
      - name: Seed Pages dashboard onto benchmark-data (if absent)
        run: |
          for f in index.html dashboard.js dashboard.css metric-labels.json competitors.json vendor/Chart.min.js; do
            cp "$src/$f" "$tmp/dev/bench/$f"
          done
          if ! cmp -s "$src/root-redirect.html" "$tmp/index.html"; then
            cp "$src/root-redirect.html" "$tmp/index.html"
          fi
"""

# Same step but a new served asset (extra.json) was added to bench/dashboard/ and
# NEVER added to the loop — the drift this gate exists to catch.
_SEED_MISSING_ONE = """\
      - name: Seed
        run: |
          for f in index.html dashboard.js dashboard.css metric-labels.json competitors.json vendor/Chart.min.js; do
            cp "$src/$f" "$tmp/dev/bench/$f"
          done
          cp "$src/root-redirect.html" "$tmp/index.html"
"""

# The root-redirect copy line was dropped while root-redirect.html still exists.
_SEED_NO_ROOT_REDIRECT = """\
      - name: Seed
        run: |
          for f in index.html dashboard.js dashboard.css metric-labels.json competitors.json vendor/Chart.min.js; do
            cp "$src/$f" "$tmp/dev/bench/$f"
          done
"""

# The seed loop is gone entirely (step rewritten) — must surface as a sentinel.
_SEED_NO_LOOP = """\
      - name: Seed
        run: |
          rsync -a "$src/" "$tmp/dev/bench/"
"""

_SERVED = [
    "index.html",
    "dashboard.js",
    "dashboard.css",
    "metric-labels.json",
    "competitors.json",
    "root-redirect.html",
    "vendor/Chart.min.js",
    "vendor/README.md",  # excluded (*.md) — never an offence
]


def self_test() -> int:
    cases = [
        # (label, workflow_text, assets, expected_offence_count)
        ("all served assets wired", _SEED_OK, _SERVED, 0),
        # README.md is excluded, so a docs-only tree never offends.
        ("docs-only asset excluded", _SEED_OK, ["vendor/README.md"], 0),
        # data.js is generated on-branch → excluded even if it appears in the tree.
        ("generated data.js excluded", _SEED_OK, ["data.js", "index.html"], 0),
        # A new served asset not in the loop → exactly one offence.
        (
            "new served asset not wired",
            _SEED_MISSING_ONE,
            _SERVED + ["extra.json"],
            1,
        ),
        # An existing served asset silently dropped from the loop → one offence.
        # (_SEED_OK keeps the root-redirect copy line, so dashboard.css is the SOLE
        # unwired asset — isolating the single-drop case.)
        (
            "served asset dropped from loop",
            _SEED_OK.replace(" dashboard.css", ""),
            _SERVED,
            1,
        ),
        # root-redirect copy line removed → root-redirect.html is now unwired.
        ("root-redirect unwired", _SEED_NO_ROOT_REDIRECT, _SERVED, 1),
        # Seed loop removed entirely → sentinel offence (step shape changed).
        ("seed loop missing → sentinel", _SEED_NO_LOOP, _SERVED, 1),
        # No assets at all → nothing to wire → pass.
        ("empty dashboard tree", _SEED_OK, [], 0),
    ]
    failures = 0
    for label, text, assets, expected in cases:
        got = len(find_offences(text, assets))
        ok = got == expected
        print(
            f"  [{'PASS' if ok else 'FAIL'}] {label}: "
            f"{got} offence(s) (want {expected})"
        )
        if not ok:
            failures += 1
    if failures:
        print(f"\nself-test: {failures} case(s) FAILED")
        return 1
    print("\nself-test: all cases PASS")
    return 0


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        description="Fail if any served-class bench/dashboard asset is not wired "
        "into the Pages publisher (bench.yml seed step) — anti-drift (bead sq-53cq)."
    )
    ap.add_argument(
        "--root",
        default=str(REPO_ROOT),
        help="repo root to check (default: this repo).",
    )
    ap.add_argument(
        "--self-test",
        action="store_true",
        help="run the hermetic logic self-test and exit.",
    )
    args = ap.parse_args(argv)

    if args.self_test:
        return self_test()

    root = Path(args.root)
    wf = root / BENCH_WORKFLOW
    if not wf.is_file():
        print(f"FAIL: cannot find {BENCH_WORKFLOW} under {root}")
        return 1
    workflow_text = wf.read_text(encoding="utf-8", errors="ignore")
    assets = tracked_dashboard_assets(root)
    offences = find_offences(workflow_text, assets)

    if not offences:
        seed = seed_list_files(workflow_text) or set()
        print(
            "dashboard publish-wiring gate: PASS — every served-class "
            f"{DASHBOARD_DIR}/ asset is wired into the Pages publisher "
            f"({len(seed)} file(s) in bench.yml's seed loop + root-redirect.html)."
        )
        return 0

    if offences == ["<seed-loop-not-found>"]:
        print("dashboard publish-wiring gate: FAIL\n")
        print(
            f"Could not locate the `for f in … ; do` seed loop in {BENCH_WORKFLOW}.\n"
            "The 'Seed Pages dashboard onto benchmark-data' step is the publisher that\n"
            f"copies {DASHBOARD_DIR}/* onto the benchmark-data branch. If you rewrote\n"
            "that step, update this gate (scripts/check-dashboard-publish-wiring.py) so\n"
            "it can still verify every served asset is propagated."
        )
        return 1

    print("dashboard publish-wiring gate: FAIL\n")
    print(
        f"These served-class {DASHBOARD_DIR}/ assets are NOT wired into the Pages\n"
        "publisher — they would land in-repo but NEVER reach the served dashboard\n"
        f"(bead sq-53cq). Add each to bench.yml's 'Seed Pages dashboard' step: the\n"
        "`for f in …` loop (for files served under dev/bench/), or the dedicated\n"
        "root-redirect copy (for root-redirect.html). If a file is intentionally NOT\n"
        "served (a *.md doc), this gate already excludes it — see the script header.\n"
    )
    for off in offences:
        print(f"    - {DASHBOARD_DIR}/{off}")
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
