#!/usr/bin/env bash
# [OPUS-5] issue #4571 (GX-11 residual / SL-B3-b) — CONSUMER-SIDE verification of the
# isolated-trusted-builder provenance attached to a published GitHub Release.
#
# WHY THIS EXISTS. release.yml#provenance and release.yml#provenance-artifacts route the
# release artifacts' provenance through `slsa-github-generator`'s trusted reusable builder, and
# scripts/tests/test_release_slsa_l3_provenance.py pins that WIRING structurally on every PR.
# But wiring is not evidence: both workflows are tag/dispatch-triggered, so nothing has ever
# executed, and compliance/slsa/controls.md therefore records SL-B3-b as **AR** (asserted, not
# independently verified). The flip to **IV** needs one thing this repo could not previously
# produce — a machine-checked verification of a REAL published release. That is what this
# script does, and release.yml runs it automatically: its `verify-provenance` job calls
# .github/workflows/release-verify.yml once the `release` job has cut the Release, so the
# evidence is produced by the first `v*` tag rather than depending on someone remembering to run
# three commands by hand. (It is driven from release.yml, NOT from release-verify.yml's
# `release: published` trigger: GitHub does not start a workflow run from an event generated by
# the workflow's own GITHUB_TOKEN, which is the token that creates the Release. That trigger is
# the out-of-band net for a release published by hand.)
#
# WHAT IT CHECKS, all fail-closed:
#   1. Both in-toto bundles are ATTACHED to the Release — `sparq-cli-<version>.intoto.jsonl`
#      (the CLI/server archives) and `sparq-artifacts-<version>.intoto.jsonl` (GUI bundles,
#      SBOM/VEX, served-surface conformance report).
#   2. `SHA256SUMS` is attached, LISTS both bundles, and every listed digest matches the bytes
#      actually published (`sha256sum -c`). A bundle absent from SHA256SUMS is a real defect:
#      the Release notes tell consumers SHA256SUMS covers what they download.
#   3. `slsa-verifier verify-artifact <asset> --provenance-path <bundle> --source-uri
#      github.com/<owner>/<repo>` passes for EVERY published asset, against one of the two
#      bundles (matching is by digest, so the version-stable alias copies verify against the
#      same bundle as the versioned originals they were copied from). An asset that verifies
#      against NEITHER bundle is reported as UNCOVERED and reds the run — that is the check
#      that would catch a lane silently dropping out of the subjects set, which a signature
#      over a smaller set would otherwise hide.
#      The ONLY assets exempt from (3) are `SHA256SUMS` and the two `.intoto.jsonl` bundles
#      themselves, exactly as the Release body states.
#   4. VACUITY GUARD: zero successful verifications is a FAILURE, not a pass. An empty (or
#      wrongly-filtered) asset directory must never read as "provenance verified".
#
# WHAT A GREEN RUN DOES *NOT* SAY. It says the provenance over these bytes was produced by a
# builder our build steps cannot reach and that it verifies against this repo — SLSA's
# unforgeable-provenance property (SL-B3-b). It does NOT say the artifacts were built inside a
# trusted builder (this is the GENERIC generator: it signs digests our build jobs reported), and
# it says nothing about the ghcr.io container image, which still attests in-band (L2). GX-11
# narrows on a green run; it does not close. Do not upgrade the wording beyond that.
#
# Usage:
#   scripts/verify-release-provenance.sh --tag v0.1.1 [--repo sparq-org/sparq] [--dir <assets>]
#     --tag   the released version string; also the version stamped into the bundle names
#     --repo  owner/name (default: sparq-org/sparq) — becomes `--source-uri github.com/<repo>`
#     --dir   a directory of ALREADY-downloaded release assets. Omitted => the assets are
#             fetched with `gh release download` into a temp dir.
#
# Requires `slsa-verifier` on PATH (or $SLSA_VERIFIER), and `gh` unless --dir is given.
# Self-tested by scripts/tests/test_verify_release_provenance.sh (docs-quality.yml).
set -euo pipefail

REPO="sparq-org/sparq"
TAG=""
ASSET_DIR=""

die() {
  echo "verify-release-provenance: ERROR: $*" >&2
  exit 1
}

while [ "$#" -gt 0 ]; do
  case "$1" in
    --tag)
      [ "$#" -ge 2 ] || die "--tag needs a value"
      TAG="$2"
      shift 2
      ;;
    --repo)
      [ "$#" -ge 2 ] || die "--repo needs a value"
      REPO="$2"
      shift 2
      ;;
    --dir)
      [ "$#" -ge 2 ] || die "--dir needs a value"
      ASSET_DIR="$2"
      shift 2
      ;;
    -h | --help)
      sed -n '/^# Usage:/,/^# Requires/p' "$0"
      exit 0
      ;;
    *)
      die "unknown argument '$1' (see --help)"
      ;;
  esac
done

[ -n "$TAG" ] || die "--tag is required (e.g. --tag v0.1.1)"

SLSA_VERIFIER="${SLSA_VERIFIER:-slsa-verifier}"
command -v "$SLSA_VERIFIER" >/dev/null 2>&1 ||
  die "'$SLSA_VERIFIER' not found on PATH. Install it (e.g. \`go install github.com/slsa-framework/slsa-verifier/v2/cli/slsa-verifier@v2.7.1\`) or set \$SLSA_VERIFIER."

# One EXIT trap for both temporaries. Written as `if` blocks, not `[ … ] && rm …`: a trailing
# false test would make the handler's last command fail, and under `set -e` that overwrites the
# script's real exit status (a PASS would exit 1).
CLEANUP_DIR=""
VERIFIER_LOG=""
cleanup() {
  if [ -n "$CLEANUP_DIR" ]; then rm -rf -- "$CLEANUP_DIR"; fi
  if [ -n "$VERIFIER_LOG" ]; then rm -f -- "$VERIFIER_LOG"; fi
}
trap cleanup EXIT

if [ -z "$ASSET_DIR" ]; then
  command -v gh >/dev/null 2>&1 ||
    die "no --dir given and \`gh\` is not installed — cannot download the release assets"
  CLEANUP_DIR="$(mktemp -d)"
  ASSET_DIR="$CLEANUP_DIR/assets"
  mkdir -p "$ASSET_DIR"
  echo "==> downloading assets of $REPO@$TAG"
  gh release download "$TAG" --repo "$REPO" --dir "$ASSET_DIR" ||
    die "\`gh release download $TAG\` failed — is the Release published and are its assets attached?"
fi

[ -d "$ASSET_DIR" ] || die "asset directory '$ASSET_DIR' does not exist"
cd "$ASSET_DIR"

CLI_BUNDLE="sparq-cli-${TAG}.intoto.jsonl"
ARTIFACTS_BUNDLE="sparq-artifacts-${TAG}.intoto.jsonl"

# ---- 1. both isolated-builder bundles attached ----------------------------------------------
for bundle in "$CLI_BUNDLE" "$ARTIFACTS_BUNDLE"; do
  [ -s "$bundle" ] ||
    die "'$bundle' is missing or empty from the Release assets — the isolated trusted builder did not produce it, or the \`release\` job did not attach it. SL-B3-b stays AR."
done
echo "OK: both isolated-builder bundles attached ($CLI_BUNDLE, $ARTIFACTS_BUNDLE)"

# ---- 2. SHA256SUMS present, covers both bundles, and matches the published bytes -------------
[ -s SHA256SUMS ] || die "SHA256SUMS is missing or empty from the Release assets"
for bundle in "$CLI_BUNDLE" "$ARTIFACTS_BUNDLE"; do
  # Field-exact: the name must be the 2nd whitespace-separated field of some record, not a
  # substring of another asset's name.
  awk -v want="$bundle" '$2 == want { found = 1 } END { exit found ? 0 : 1 }' SHA256SUMS ||
    die "'$bundle' is not listed in SHA256SUMS — the Release notes claim SHA256SUMS covers every attached asset"
done
sha256sum -c SHA256SUMS >/dev/null ||
  die "SHA256SUMS does not match the published bytes (\`sha256sum -c SHA256SUMS\` failed)"
echo "OK: SHA256SUMS verifies and lists both bundles"

# ---- 3. slsa-verifier over every published asset ---------------------------------------------
SOURCE_URI="github.com/${REPO}"
cli_verified=0
artifacts_verified=0
uncovered=""
VERIFIER_LOG="$(mktemp)"

shopt -s nullglob
for asset in *; do
  [ -f "$asset" ] || continue
  case "$asset" in
    SHA256SUMS | *.intoto.jsonl) continue ;;
  esac
  if "$SLSA_VERIFIER" verify-artifact "$asset" \
    --provenance-path "$CLI_BUNDLE" --source-uri "$SOURCE_URI" >"$VERIFIER_LOG" 2>&1; then
    cli_verified=$((cli_verified + 1))
    echo "  verified (archives bundle):  $asset"
  elif "$SLSA_VERIFIER" verify-artifact "$asset" \
    --provenance-path "$ARTIFACTS_BUNDLE" --source-uri "$SOURCE_URI" >"$VERIFIER_LOG" 2>&1; then
    artifacts_verified=$((artifacts_verified + 1))
    echo "  verified (artifacts bundle): $asset"
  else
    uncovered="${uncovered}${uncovered:+ }${asset}"
    echo "  UNCOVERED:                   $asset" >&2
    sed 's/^/      /' "$VERIFIER_LOG" >&2
  fi
done

if [ -n "$uncovered" ]; then
  die "these published assets verify against NEITHER isolated-builder bundle: $uncovered
Every asset but SHA256SUMS and the .intoto.jsonl bundles must be a subject of one of them — an
uncovered asset means a lane dropped out of the subjects set, so the signature covers less than
the compliance estate claims. SL-B3-b stays AR."
fi

total=$((cli_verified + artifacts_verified))
[ "$total" -gt 0 ] ||
  die "zero assets were verified — an empty asset set must never read as 'provenance verified'"
[ "$cli_verified" -gt 0 ] ||
  die "no asset verified against '$CLI_BUNDLE' — the archives lane produced a bundle covering nothing it published"
[ "$artifacts_verified" -gt 0 ] ||
  die "no asset verified against '$ARTIFACTS_BUNDLE' — the GUI/SBOM/conformance lane produced a bundle covering nothing it published"

cat <<EOF

==> EVIDENCE (paste into compliance/slsa/evidence.md)
    release ............ ${REPO}@${TAG}
    source-uri ......... ${SOURCE_URI}
    archives bundle .... ${CLI_BUNDLE} — ${cli_verified} asset(s) verified
    artifacts bundle ... ${ARTIFACTS_BUNDLE} — ${artifacts_verified} asset(s) verified
    SHA256SUMS ......... verifies, and lists both bundles
    verifier ........... $("$SLSA_VERIFIER" version 2>&1 | head -1 || echo "unknown")

    Scope of this result: the PROVENANCE over these bytes is unforgeable by the build
    (SL-B3-b). It is NOT a claim that the artifacts were built inside a trusted builder
    (generic generator), and it does NOT cover the ghcr.io container image (in-band, L2).
EOF
echo "verify-release-provenance: PASS (${total} assets)"
