#!/usr/bin/env bash
# sq-hmd7l.16 — rdf-canon (zkp-ld/yamdan Rust crate) adapter for the
# bench/canon RDFC-1.0 comparison panel.
#
# The rdf-canon crate ships no CLI, so this adapter scaffolds a tiny scratch
# cargo project (gather-time only — NOT a workspace member, NOT a committed
# dependency) that parses N-Quads with oxttl 0.1 / oxrdf 0.2 (the crate's own
# term model) and calls rdf_canon::canonicalize_quads directly. The shim speaks
# the SAME CLI + exit-code contract as sparq's runner
# (crates/sparq-canon/examples/canon_bench.rs), so bench/canon/run.sh drives
# every engine uniformly.
#
# HONESTY NOTE: sparq-canon itself DELEGATES the RDFC-1.0 algorithm to this
# same crate (rdf-canon, pinned in the workspace Cargo.toml). With the default
# CANON_RDF_CANON_VERSION (matching sparq's pin) this column measures sparq's
# oxrdf-0.3<->0.2 N-Quads bridge + guard configuration overhead, NOT an
# independent implementation. Override the version to compare against a newer
# upstream release. The independent-implementation column is rdf-canonize (JS).
#
# USAGE
#   canon_adapter.sh --build                                  # scaffold + build; prints bin path
#   canon_adapter.sh --engine rdf-canon --input <f.nq> [--sha384]
#
# ENV
#   CANON_RDF_CANON_VERSION  crates.io version to pin (default 0.15.3 = sparq's own pin)
#   CANON_SCRATCH_DIR        scratch project dir
#                            (default ${XDG_CACHE_HOME:-$HOME/.cache}/sparq-bench/rdf-canon-cli)
#
# Exit codes (same contract as canon_bench):
#   0 ok | 2 canonicalization rejected (fail-closed guard) | 3 parse error | 1 usage/IO
set -euo pipefail

VER="${CANON_RDF_CANON_VERSION:-0.15.3}"
SCRATCH="${CANON_SCRATCH_DIR:-${XDG_CACHE_HOME:-$HOME/.cache}/sparq-bench/rdf-canon-cli}"
BIN="$SCRATCH/target/release/rdf-canon-cli"

build() {
  mkdir -p "$SCRATCH/src"
  cat > "$SCRATCH/Cargo.toml" <<EOF
# generated by scripts/bench-adapters/canon_adapter.sh — gather-time scratch CLI,
# never part of the sparq workspace. Pins rdf-canon $VER.
[package]
name = "rdf-canon-cli"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
rdf-canon = "=$VER"
oxrdf = "=0.2.4"
oxttl = "=0.1.8"
sha2 = "0.10"

[workspace]
EOF
  cat > "$SCRATCH/src/main.rs" <<'EOF'
// generated by scripts/bench-adapters/canon_adapter.sh — rdf-canon CLI shim.
// Same CLI + exit contract as sparq's canon_bench runner.
use std::time::Instant;

const RDF_CANON_VERSION: &str = "__RDF_CANON_VERSION__";

fn main() {
    eprintln!("version={}", RDF_CANON_VERSION);
    let args: Vec<String> = std::env::args().skip(1).collect();
    let (sha384, path) = match args.as_slice() {
        [c, f, p] if c == "canon" && f == "--sha384" => (true, p.clone()),
        [c, p] if c == "canon" => (false, p.clone()),
        _ => {
            eprintln!("usage: rdf-canon-cli canon [--sha384] <input.nq>");
            std::process::exit(1);
        }
    };
    let input = match std::fs::read(&path) {
        Ok(b) => b,
        Err(e) => {
            eprintln!("rdf-canon-cli: read {}: {}", path, e);
            std::process::exit(1);
        }
    };
    let t = Instant::now();
    let mut quads: Vec<oxrdf::Quad> = Vec::new();
    for item in oxttl::NQuadsParser::new().for_reader(input.as_slice()) {
        match item {
            Ok(q) => quads.push(q),
            Err(e) => {
                eprintln!("rdf-canon-cli: parse {}: {}", path, e);
                std::process::exit(3);
            }
        }
    }
    eprintln!("parse_us={}", t.elapsed().as_micros());
    let t = Instant::now();
    let result = if sha384 {
        let opts = rdf_canon::CanonicalizationOptions::default();
        rdf_canon::canonicalize_quads_with::<sha2::Sha384>(&quads, &opts)
    } else {
        rdf_canon::canonicalize_quads(&quads)
    };
    let canon_us = t.elapsed().as_micros();
    eprintln!("canon_us={}", canon_us);
    match result {
        Ok(canonical) => {
            print!("{}", canonical);
            std::process::exit(0);
        }
        Err(e) => {
            // Fail-closed rejection (the crate's HNDQ call-limit guard).
            eprintln!("rdf-canon-cli: rejected (fail-closed): {}", e);
            std::process::exit(2);
        }
    }
}
EOF
  sed -i "s/__RDF_CANON_VERSION__/$VER/" "$SCRATCH/src/main.rs"
  # Prefer the local cargo cache (rdf-canon is a sparq workspace dep, so the
  # matching-version build is usually offline-clean); fall back to the network.
  if ! (cd "$SCRATCH" && cargo build --release --offline >&2); then
    echo "canon_adapter: offline build failed; retrying with network" >&2
    (cd "$SCRATCH" && cargo build --release >&2)
  fi
  echo "version=$VER" >&2
  echo "$BIN"
}

case "${1:-}" in
  --build)
    build
    ;;
  --engine)
    [ "${2:-}" = "rdf-canon" ] || { echo "canon_adapter: unknown engine '${2:-}'" >&2; exit 1; }
    [ "${3:-}" = "--input" ] || { echo "canon_adapter: expected --input <file>" >&2; exit 1; }
    INPUT="${4:-}"
    [ -n "$INPUT" ] || { echo "canon_adapter: missing input file" >&2; exit 1; }
    SHA384_FLAG=()
    [ "${5:-}" = "--sha384" ] && SHA384_FLAG=(--sha384)
    if [ ! -x "$BIN" ]; then
      echo "canon_adapter: scratch CLI not built — run: $0 --build" >&2
      exit 1
    fi
    echo "version=$VER" >&2
    exec "$BIN" canon "${SHA384_FLAG[@]}" "$INPUT"
    ;;
  *)
    echo "usage: canon_adapter.sh --build | --engine rdf-canon --input <f.nq> [--sha384]" >&2
    exit 1
    ;;
esac
