#!/usr/bin/env bash
# sq-hmd7l.14 — oxrdfio (Oxigraph's RDF I/O crate) adapter for the
# bench/serialize serialization-throughput panel.
#
# oxrdfio ships no CLI, so this adapter scaffolds a tiny scratch cargo project
# (gather-time only — NOT a workspace member, NOT a committed dependency) that
# parses N-Triples and re-serializes via oxrdfio's RdfParser/RdfSerializer.
# The shim speaks the SAME CLI + stderr-metric contract as sparq's runner
# (crates/sparq-engine-serialize/examples/serialize_bench.rs `pipe` mode):
# materialize the parsed quads in memory, then serialize — like-for-like with
# sparq's store-then-write pipeline (the serdi / rapper / riot columns run
# as-shipped, whatever their internal pipeline is; labelled in the envelope).
#
# The default pin (0.2.5) depends on oxrdf =0.3.3 / oxttl =0.2.3 — the exact
# family the sparq workspace itself pins — so the column isolates writer-path
# differences, not term-model-generation drift.
#
# USAGE
#   serialize_oxrdfio_adapter.sh --build            # scaffold + build; prints bin path
#   <bin> <input.nt> <turtle|ntriples|nquads|trig> <out-file>
#   <bin> --version
#
# ENV
#   SERIALIZE_OXRDFIO_VERSION  crates.io version to pin (default 0.2.5)
#   SERIALIZE_SCRATCH_DIR      scratch project dir
#                              (default ${XDG_CACHE_HOME:-$HOME/.cache}/sparq-bench/oxrdfio-serialize-cli)
#
# Exit codes (same contract as serialize_bench pipe): 0 ok | 3 parse error | 1 usage/IO
set -euo pipefail

VER="${SERIALIZE_OXRDFIO_VERSION:-0.2.5}"
SCRATCH="${SERIALIZE_SCRATCH_DIR:-${XDG_CACHE_HOME:-$HOME/.cache}/sparq-bench/oxrdfio-serialize-cli}"
BIN="$SCRATCH/target/release/oxrdfio-serialize-cli"

build() {
  mkdir -p "$SCRATCH/src"
  cat > "$SCRATCH/Cargo.toml" <<EOF
# generated by scripts/bench-adapters/serialize_oxrdfio_adapter.sh — gather-time
# scratch CLI, never part of the sparq workspace. Pins oxrdfio $VER.
[package]
name = "oxrdfio-serialize-cli"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
oxrdfio = "=$VER"

[workspace]

[profile.release]
opt-level = 3
EOF
  cat > "$SCRATCH/src/main.rs" <<EOF
// generated by scripts/bench-adapters/serialize_oxrdfio_adapter.sh — oxrdfio shim.
// Same CLI + stderr-metric contract as sparq's serialize_bench \`pipe\` mode.
const OXRDFIO_VERSION: &str = "$VER";
EOF
  cat >> "$SCRATCH/src/main.rs" <<'EOF'
use oxrdfio::{RdfFormat, RdfParser, RdfSerializer};
use std::io::BufWriter;
use std::time::Instant;

fn fmt_of(s: &str) -> Option<RdfFormat> {
    Some(match s {
        "turtle" => RdfFormat::Turtle,
        "ntriples" | "nt" => RdfFormat::NTriples,
        "nquads" => RdfFormat::NQuads,
        "trig" => RdfFormat::TriG,
        _ => return None,
    })
}

fn main() {
    let args: Vec<String> = std::env::args().skip(1).collect();
    if args.len() == 1 && args[0] == "--version" {
        eprintln!("version=oxrdfio {}", OXRDFIO_VERSION);
        return;
    }
    let (input, fmt, out) = match args.as_slice() {
        [i, f, o] => (i, f, o),
        _ => {
            eprintln!("usage: oxrdfio-serialize-cli <input.nt> <turtle|ntriples|nquads|trig> <out-file> | --version");
            std::process::exit(1);
        }
    };
    let Some(fmt) = fmt_of(fmt) else {
        eprintln!("oxrdfio-serialize-cli: unknown format {}", fmt);
        std::process::exit(1);
    };
    let file = match std::fs::File::open(input) {
        Ok(f) => f,
        Err(e) => {
            eprintln!("oxrdfio-serialize-cli: open {}: {}", input, e);
            std::process::exit(1);
        }
    };
    // Materialize-then-serialize, mirroring sparq's `pipe` (store, then write).
    let t = Instant::now();
    let quads: Vec<_> = match RdfParser::from_format(RdfFormat::NTriples)
        .for_reader(std::io::BufReader::new(file))
        .collect::<Result<_, _>>()
    {
        Ok(q) => q,
        Err(e) => {
            eprintln!("oxrdfio-serialize-cli: parse {}: {}", input, e);
            std::process::exit(3);
        }
    };
    let parse_us = t.elapsed().as_micros();

    let out_file = match std::fs::File::create(out) {
        Ok(f) => f,
        Err(e) => {
            eprintln!("oxrdfio-serialize-cli: create {}: {}", out, e);
            std::process::exit(1);
        }
    };
    let t = Instant::now();
    // The same prefix policy the sparq runner uses (bench corpus vocab +
    // rdf/xsd), so prefix-compressing formats do comparable compression work.
    let mut ser = RdfSerializer::from_format(fmt);
    for (p, ns) in [
        ("sb", "http://sparq.dev/bench/serialize/"),
        ("sbv", "http://sparq.dev/bench/serialize/vocab#"),
        ("rdf", "http://www.w3.org/1999/02/22-rdf-syntax-ns#"),
        ("xsd", "http://www.w3.org/2001/XMLSchema#"),
    ] {
        ser = ser.with_prefix(p, ns).expect("static prefix IRIs are valid");
    }
    let mut w = ser.for_writer(BufWriter::new(out_file));
    for q in &quads {
        if let Err(e) = w.serialize_quad(q) {
            eprintln!("oxrdfio-serialize-cli: serialize: {}", e);
            std::process::exit(1);
        }
    }
    let inner = match w.finish() {
        Ok(i) => i,
        Err(e) => {
            eprintln!("oxrdfio-serialize-cli: finish: {}", e);
            std::process::exit(1);
        }
    };
    drop(inner);
    let ser_us = t.elapsed().as_micros();
    let bytes = std::fs::metadata(out).map(|m| m.len()).unwrap_or(0);
    eprintln!("parse_us={}", parse_us);
    eprintln!("ser_us={}", ser_us);
    eprintln!("out_bytes={}", bytes);
}
EOF
  (cd "$SCRATCH" && cargo build --release >&2)
  echo "$BIN"
}

case "${1:-}" in
  --build) build ;;
  *)
    echo "usage: serialize_oxrdfio_adapter.sh --build   # then invoke the printed binary directly" >&2
    exit 1
    ;;
esac
